/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "widget-action-items": string;
  readonly "widget-action-link": string;
  readonly "widget-actions": string;
};
export = styles;

