/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "indicator": string;
  readonly "is-minimal-variant": string;
  readonly "is-overflowing-first": string;
  readonly "is-overflowing-last": string;
  readonly "tab": string;
  readonly "tab-chevron": string;
  readonly "tab-children": string;
  readonly "tablist": string;
};
export = styles;

