/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "container": string;
  readonly "iframe": string;
  readonly "loading": string;
  readonly "overlay": string;
  readonly "previewWrap": string;
  readonly "urlBar": string;
  readonly "urlFavicon": string;
  readonly "urlField": string;
  readonly "urlIcon": string;
  readonly "urlText": string;
};
export = styles;

