/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "actions-fold-out": string;
  readonly "actions-slide-in": string;
  readonly "edit-actions-divider": string;
  readonly "edit-actions-enter": string;
  readonly "edit-actions-exit": string;
};
export = styles;

