/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "current": string;
  readonly "list": string;
  readonly "separator": string;
};
export = styles;

