/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "container": string;
  readonly "locationPickerInWidget": string;
  readonly "noLocationSelected": string;
  readonly "statusText": string;
};
export = styles;

