/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "chip": string;
  readonly "chip-content": string;
  readonly "chip-prefix": string;
  readonly "chip-remove": string;
  readonly "positioner": string;
};
export = styles;

