<?php
/**
 * Compatibility shims for KSES (content filtering) for WordPress 7.0.
 *
 * @package gutenberg
 */

/**
 * Add 'display' to the list of safe CSS properties.
 * This is needed for viewport visibility support.
 *
 * @param array $attr List of allowed CSS attributes.
 * @return array Modified list of allowed CSS attributes.
 */
function gutenberg_add_display_to_safe_style_css( $attr ) {
	if ( ! in_array( 'display', $attr, true ) ) {
		$attr[] = 'display';
	}

	return $attr;
}
add_filter( 'safe_style_css', 'gutenberg_add_display_to_safe_style_css' );

/**
 * Add background-clip and related vendor-prefixed properties to the list of
 * safe CSS properties. Without these, `safecss_filter_attr()` strips the
 * declarations generated by the background-clip block support, which causes
 * the style engine to return an empty `css` string.
 *
 * @param string[] $attr List of allowed CSS attributes.
 * @return string[] Modified list of allowed CSS attributes.
 */
function gutenberg_add_background_clip_to_safe_style_css( $attr ) {
	$background_clip_attrs = array(
		'background-clip',
		'-webkit-background-clip',
		'-webkit-text-fill-color',
	);

	foreach ( $background_clip_attrs as $background_clip_attr ) {
		if ( ! in_array( $background_clip_attr, $attr, true ) ) {
			$attr[] = $background_clip_attr;
		}
	}

	return $attr;
}
add_filter( 'safe_style_css', 'gutenberg_add_background_clip_to_safe_style_css' );
