/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "banner": string;
  readonly "bannerContent": string;
  readonly "bannerLink": string;
};
export = styles;

