/**
 * This file is generated by the @terrazzo/plugin-known-wpds-css-variables plugin.
 * Do not edit this file directly.
 */

export default {
	'--wpds-border-radius-x-small': {
		'.': '1px',
	},
	'--wpds-border-radius-small': {
		'.': '2px',
	},
	'--wpds-border-radius-medium': {
		'.': '4px',
	},
	'--wpds-border-radius-large': {
		'.': '8px',
	},
	'--wpds-border-width-focus': {
		'.': '2px',
		'high-dpi': '1.5px',
	},
	'--wpds-color-bg-surface-neutral': {
		'.': 'var(--wpds-color-private-bg-surface2)',
	},
	'--wpds-color-bg-surface-neutral-strong': {
		'.': 'var(--wpds-color-private-bg-surface3)',
	},
	'--wpds-color-bg-surface-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-surface1)',
	},
	'--wpds-color-bg-surface-brand': {
		'.': 'var(--wpds-color-private-primary-surface1)',
	},
	'--wpds-color-bg-surface-success': {
		'.': 'var(--wpds-color-private-success-surface4)',
	},
	'--wpds-color-bg-surface-success-weak': {
		'.': 'var(--wpds-color-private-success-surface2)',
	},
	'--wpds-color-bg-surface-info': {
		'.': 'var(--wpds-color-private-info-surface4)',
	},
	'--wpds-color-bg-surface-info-weak': {
		'.': 'var(--wpds-color-private-info-surface2)',
	},
	'--wpds-color-bg-surface-warning': {
		'.': 'var(--wpds-color-private-warning-surface4)',
	},
	'--wpds-color-bg-surface-warning-weak': {
		'.': 'var(--wpds-color-private-warning-surface2)',
	},
	'--wpds-color-bg-surface-caution': {
		'.': 'var(--wpds-color-private-caution-surface4)',
	},
	'--wpds-color-bg-surface-caution-weak': {
		'.': 'var(--wpds-color-private-caution-surface2)',
	},
	'--wpds-color-bg-surface-error': {
		'.': 'var(--wpds-color-private-error-surface4)',
	},
	'--wpds-color-bg-surface-error-weak': {
		'.': 'var(--wpds-color-private-error-surface2)',
	},
	'--wpds-color-bg-interactive-neutral': {
		'.': '#00000000',
	},
	'--wpds-color-bg-interactive-neutral-active': {
		'.': 'var(--wpds-color-private-bg-surface4)',
	},
	'--wpds-color-bg-interactive-neutral-disabled': {
		'.': 'var(--wpds-color-private-bg-surface5)',
	},
	'--wpds-color-bg-interactive-neutral-strong': {
		'.': 'var(--wpds-color-private-bg-bg-fill-inverted1)',
	},
	'--wpds-color-bg-interactive-neutral-strong-active': {
		'.': 'var(--wpds-color-private-bg-bg-fill-inverted2)',
	},
	'--wpds-color-bg-interactive-neutral-strong-disabled': {
		'.': 'var(--wpds-color-private-bg-surface6)',
	},
	'--wpds-color-bg-interactive-neutral-weak': {
		'.': '#00000000',
	},
	'--wpds-color-bg-interactive-neutral-weak-active': {
		'.': 'var(--wpds-color-private-bg-surface4)',
	},
	'--wpds-color-bg-interactive-neutral-weak-disabled': {
		'.': 'var(--wpds-color-private-bg-surface5)',
	},
	'--wpds-color-bg-interactive-brand': {
		'.': '#00000000',
	},
	'--wpds-color-bg-interactive-brand-active': {
		'.': 'var(--wpds-color-private-primary-surface2)',
	},
	'--wpds-color-bg-interactive-brand-disabled': {
		'.': 'var(--wpds-color-private-bg-surface5)',
	},
	'--wpds-color-bg-interactive-brand-strong': {
		'.': 'var(--wpds-color-private-primary-bg-fill1)',
	},
	'--wpds-color-bg-interactive-brand-strong-active': {
		'.': 'var(--wpds-color-private-primary-bg-fill2)',
	},
	'--wpds-color-bg-interactive-brand-strong-disabled': {
		'.': 'var(--wpds-color-private-bg-surface6)',
	},
	'--wpds-color-bg-interactive-brand-weak': {
		'.': '#00000000',
	},
	'--wpds-color-bg-interactive-brand-weak-active': {
		'.': 'var(--wpds-color-private-primary-surface4)',
	},
	'--wpds-color-bg-interactive-brand-weak-disabled': {
		'.': 'var(--wpds-color-private-bg-surface5)',
	},
	'--wpds-color-bg-track-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-stroke1)',
	},
	'--wpds-color-bg-track-neutral': {
		'.': 'var(--wpds-color-private-bg-stroke2)',
	},
	'--wpds-color-bg-thumb-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-stroke3)',
	},
	'--wpds-color-bg-thumb-neutral-weak-active': {
		'.': 'var(--wpds-color-private-bg-stroke4)',
	},
	'--wpds-color-bg-thumb-brand': {
		'.': 'var(--wpds-color-private-primary-stroke3)',
	},
	'--wpds-color-bg-thumb-brand-active': {
		'.': 'var(--wpds-color-private-primary-stroke3)',
	},
	'--wpds-color-bg-thumb-brand-disabled': {
		'.': 'var(--wpds-color-private-bg-stroke2)',
	},
	'--wpds-color-fg-content-neutral': {
		'.': 'var(--wpds-color-private-bg-fg-surface4)',
	},
	'--wpds-color-fg-content-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-fg-surface3)',
	},
	'--wpds-color-fg-content-success': {
		'.': 'var(--wpds-color-private-success-fg-surface4)',
	},
	'--wpds-color-fg-content-success-weak': {
		'.': 'var(--wpds-color-private-success-fg-surface3)',
	},
	'--wpds-color-fg-content-info': {
		'.': 'var(--wpds-color-private-info-fg-surface4)',
	},
	'--wpds-color-fg-content-info-weak': {
		'.': 'var(--wpds-color-private-info-fg-surface3)',
	},
	'--wpds-color-fg-content-warning': {
		'.': 'var(--wpds-color-private-warning-fg-surface4)',
	},
	'--wpds-color-fg-content-warning-weak': {
		'.': 'var(--wpds-color-private-warning-fg-surface3)',
	},
	'--wpds-color-fg-content-caution': {
		'.': 'var(--wpds-color-private-caution-fg-surface4)',
	},
	'--wpds-color-fg-content-caution-weak': {
		'.': 'var(--wpds-color-private-caution-fg-surface3)',
	},
	'--wpds-color-fg-content-error': {
		'.': 'var(--wpds-color-private-error-fg-surface4)',
	},
	'--wpds-color-fg-content-error-weak': {
		'.': 'var(--wpds-color-private-error-fg-surface3)',
	},
	'--wpds-color-fg-interactive-neutral': {
		'.': 'var(--wpds-color-private-bg-fg-surface4)',
	},
	'--wpds-color-fg-interactive-neutral-active': {
		'.': 'var(--wpds-color-private-bg-fg-surface4)',
	},
	'--wpds-color-fg-interactive-neutral-disabled': {
		'.': 'var(--wpds-color-private-bg-fg-surface2)',
	},
	'--wpds-color-fg-interactive-neutral-strong': {
		'.': 'var(--wpds-color-private-bg-fg-fill-inverted)',
	},
	'--wpds-color-fg-interactive-neutral-strong-active': {
		'.': 'var(--wpds-color-private-bg-fg-fill-inverted)',
	},
	'--wpds-color-fg-interactive-neutral-strong-disabled': {
		'.': 'var(--wpds-color-private-bg-fg-surface3)',
	},
	'--wpds-color-fg-interactive-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-fg-surface3)',
	},
	'--wpds-color-fg-interactive-neutral-weak-disabled': {
		'.': 'var(--wpds-color-private-bg-fg-surface2)',
	},
	'--wpds-color-fg-interactive-brand': {
		'.': 'var(--wpds-color-private-primary-fg-surface3)',
	},
	'--wpds-color-fg-interactive-brand-active': {
		'.': 'var(--wpds-color-private-primary-fg-surface3)',
	},
	'--wpds-color-fg-interactive-brand-disabled': {
		'.': 'var(--wpds-color-private-bg-fg-surface2)',
	},
	'--wpds-color-fg-interactive-brand-strong': {
		'.': 'var(--wpds-color-private-primary-fg-fill)',
	},
	'--wpds-color-fg-interactive-brand-strong-active': {
		'.': 'var(--wpds-color-private-primary-fg-fill)',
	},
	'--wpds-color-fg-interactive-brand-strong-disabled': {
		'.': 'var(--wpds-color-private-bg-fg-surface3)',
	},
	'--wpds-color-stroke-surface-neutral': {
		'.': 'var(--wpds-color-private-bg-stroke2)',
	},
	'--wpds-color-stroke-surface-neutral-weak': {
		'.': 'var(--wpds-color-private-bg-stroke1)',
	},
	'--wpds-color-stroke-surface-neutral-strong': {
		'.': 'var(--wpds-color-private-bg-stroke3)',
	},
	'--wpds-color-stroke-surface-brand': {
		'.': 'var(--wpds-color-private-primary-stroke1)',
	},
	'--wpds-color-stroke-surface-brand-strong': {
		'.': 'var(--wpds-color-private-primary-stroke3)',
	},
	'--wpds-color-stroke-surface-success': {
		'.': 'var(--wpds-color-private-success-stroke1)',
	},
	'--wpds-color-stroke-surface-success-strong': {
		'.': 'var(--wpds-color-private-success-stroke3)',
	},
	'--wpds-color-stroke-surface-info': {
		'.': 'var(--wpds-color-private-info-stroke1)',
	},
	'--wpds-color-stroke-surface-info-strong': {
		'.': 'var(--wpds-color-private-info-stroke3)',
	},
	'--wpds-color-stroke-surface-warning': {
		'.': 'var(--wpds-color-private-warning-stroke1)',
	},
	'--wpds-color-stroke-surface-warning-strong': {
		'.': 'var(--wpds-color-private-warning-stroke3)',
	},
	'--wpds-color-stroke-surface-error': {
		'.': 'var(--wpds-color-private-error-stroke1)',
	},
	'--wpds-color-stroke-surface-error-strong': {
		'.': 'var(--wpds-color-private-error-stroke3)',
	},
	'--wpds-color-stroke-interactive-neutral': {
		'.': 'var(--wpds-color-private-bg-stroke3)',
	},
	'--wpds-color-stroke-interactive-neutral-active': {
		'.': 'var(--wpds-color-private-bg-stroke4)',
	},
	'--wpds-color-stroke-interactive-neutral-disabled': {
		'.': 'var(--wpds-color-private-bg-stroke2)',
	},
	'--wpds-color-stroke-interactive-neutral-strong': {
		'.': 'var(--wpds-color-private-bg-stroke4)',
	},
	'--wpds-color-stroke-interactive-brand': {
		'.': 'var(--wpds-color-private-primary-stroke3)',
	},
	'--wpds-color-stroke-interactive-brand-active': {
		'.': 'var(--wpds-color-private-primary-stroke4)',
	},
	'--wpds-color-stroke-interactive-brand-disabled': {
		'.': 'var(--wpds-color-private-bg-stroke2)',
	},
	'--wpds-color-stroke-interactive-error-strong': {
		'.': 'var(--wpds-color-private-error-stroke3)',
	},
	'--wpds-color-stroke-focus-brand': {
		'.': 'var(--wpds-color-private-primary-stroke3)',
	},
	'--wpds-dimension-base': {
		'.': 'var(--wpds-dimension-private-space-10)',
	},
	'--wpds-dimension-padding-surface-x-small': {
		'.': 'var(--wpds-dimension-private-space-20)',
	},
	'--wpds-dimension-padding-surface-small': {
		'.': 'var(--wpds-dimension-private-space-30)',
	},
	'--wpds-dimension-padding-surface-medium': {
		'.': 'var(--wpds-dimension-private-space-40)',
	},
	'--wpds-dimension-padding-surface-large': {
		'.': 'var(--wpds-dimension-private-space-60)',
	},
	'--wpds-elevation-x-small': {
		'.': '0 1px 1px 0 #00000008, 0 1px 2px 0 #00000005, 0 3px 3px 0 #00000005, 0 4px 4px 0 #00000003',
	},
	'--wpds-elevation-small': {
		'.': '0 1px 2px 0 #0000000d, 0 2px 3px 0 #0000000a, 0 6px 6px 0 #00000008, 0 8px 8px 0 #00000005',
	},
	'--wpds-elevation-medium': {
		'.': '0 2px 3px 0 #0000000d, 0 4px 5px 0 #0000000a, 0 12px 12px 0 #00000008, 0 16px 16px 0 #00000005',
	},
	'--wpds-elevation-large': {
		'.': '0 5px 15px 0 #00000014, 0 15px 27px 0 #00000012, 0 30px 36px 0 #0000000a, 0 50px 43px 0 #00000005',
	},
	'--wpds-font-family-heading': {
		'.': '-apple-system, system-ui, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", sans-serif',
	},
	'--wpds-font-family-body': {
		'.': '-apple-system, system-ui, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", sans-serif',
	},
	'--wpds-font-family-mono': {
		'.': '"Menlo", "Consolas", monaco, monospace',
	},
	'--wpds-font-size-x-small': {
		'.': '11px',
	},
	'--wpds-font-size-small': {
		'.': '12px',
	},
	'--wpds-font-size-medium': {
		'.': '13px',
	},
	'--wpds-font-size-large': {
		'.': '15px',
	},
	'--wpds-font-size-x-large': {
		'.': '20px',
	},
	'--wpds-font-size-2x-large': {
		'.': '32px',
	},
	'--wpds-font-line-height-x-small': {
		'.': '16px',
	},
	'--wpds-font-line-height-small': {
		'.': '20px',
	},
	'--wpds-font-line-height-medium': {
		'.': '24px',
	},
	'--wpds-font-line-height-large': {
		'.': '28px',
	},
	'--wpds-font-line-height-x-large': {
		'.': '32px',
	},
	'--wpds-font-line-height-2x-large': {
		'.': '40px',
	},
} as Record< string, Record< string, string > >;
