/*
 * This file is generated by the @wordpress/terrazzo-plugin-typescript-types plugin.
 * Do not edit this file directly.
 */

/**
 * Size scale for padding tokens.
 */
export type PaddingSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';

/**
 * Size scale for gap tokens.
 */
export type GapSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';

/**
 * Size scale for border radius tokens.
 */
export type BorderRadiusSize = 'xs' | 'sm' | 'md' | 'lg';

/**
 * Size scale for border width tokens.
 */
export type BorderWidthSize = 'xs' | 'sm' | 'md' | 'lg' | 'focus';

/**
 * Target elements that tokens can be applied to.
 */
export type Target =
	| 'surface'
	| 'interactive'
	| 'track'
	| 'thumb'
	| 'content'
	| 'focus';

/**
 * Background color variants for surface elements.
 */
export type SurfaceBackgroundColor =
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak'
	| 'brand'
	| 'success'
	| 'success-weak'
	| 'info'
	| 'info-weak'
	| 'warning'
	| 'warning-weak'
	| 'caution'
	| 'caution-weak'
	| 'error'
	| 'error-weak';

/**
 * Background color variants for interactive elements.
 */
export type InteractiveBackgroundColor =
	| 'neutral-strong'
	| 'neutral-weak'
	| 'brand-strong'
	| 'brand-weak'
	| 'error'
	| 'error-strong'
	| 'error-weak';

/**
 * Foreground color variants for content text and icons.
 */
export type ContentForegroundColor =
	| 'neutral'
	| 'neutral-weak'
	| 'success'
	| 'success-weak'
	| 'info'
	| 'info-weak'
	| 'warning'
	| 'warning-weak'
	| 'caution'
	| 'caution-weak'
	| 'error'
	| 'error-weak';

/**
 * Foreground color variants for interactive element text and icons.
 */
export type InteractiveForegroundColor =
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak'
	| 'brand'
	| 'brand-strong'
	| 'error'
	| 'error-strong';

/**
 * Stroke color variants for surface borders.
 */
export type SurfaceStrokeColor =
	| 'neutral'
	| 'neutral-weak'
	| 'neutral-strong'
	| 'brand'
	| 'brand-strong'
	| 'success'
	| 'success-strong'
	| 'info'
	| 'info-strong'
	| 'warning'
	| 'warning-strong'
	| 'error'
	| 'error-strong';

/**
 * Stroke color variants for interactive element borders.
 */
export type InteractiveStrokeColor =
	| 'neutral'
	| 'neutral-strong'
	| 'brand'
	| 'error'
	| 'error-strong';

/**
 * Foreground color variants for text elements.
 */
export type ForegroundColor =
	| 'neutral'
	| 'neutral-weak'
	| 'success'
	| 'success-weak'
	| 'info'
	| 'info-weak'
	| 'warning'
	| 'warning-weak'
	| 'caution'
	| 'caution-weak'
	| 'error'
	| 'error-weak'
	| 'neutral-active'
	| 'neutral-disabled'
	| 'neutral-strong'
	| 'neutral-strong-active'
	| 'neutral-strong-disabled'
	| 'neutral-weak-disabled'
	| 'brand'
	| 'brand-active'
	| 'brand-strong'
	| 'brand-strong-active'
	| 'error-active'
	| 'error-strong'
	| 'error-strong-active';

/**
 * Font family variants.
 */
export type FontFamily = 'heading' | 'body' | 'mono';

/**
 * Font size scale.
 */
export type FontSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/**
 * Font weight variants.
 */
export type FontWeight = 'regular' | 'medium';

/**
 * Line height scale.
 */
export type LineHeight = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
