/**
 * This file is generated by the @wordpress/terrazzo-plugin-typescript-types plugin.
 * Do not edit this file directly.
 */

/**
 * Size scale for padding tokens.
 */
export type PaddingSize = '2xs' | 'lg' | 'md' | 'sm' | 'xs';

/**
 * Size scale for gap tokens.
 */
export type GapSize = '2xs' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';

/**
 * Size scale for border radius tokens.
 */
export type BorderRadiusSize = 'lg' | 'md' | 'sm' | 'xs';

/**
 * Size scale for border width tokens.
 */
export type BorderWidthSize = 'lg' | 'md' | 'sm' | 'xs';

/**
 * Target elements that tokens can be applied to.
 */
export type Target =
	| 'content'
	| 'focus'
	| 'interactive'
	| 'surface'
	| 'thumb'
	| 'track';

/**
 * Background color variants for surface elements.
 */
export type SurfaceBackgroundColor =
	| 'brand'
	| 'caution'
	| 'caution-weak'
	| 'error'
	| 'error-weak'
	| 'info'
	| 'info-weak'
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak'
	| 'success'
	| 'success-weak'
	| 'warning'
	| 'warning-weak';

/**
 * Background color variants for interactive elements.
 */
export type InteractiveBackgroundColor =
	| 'brand'
	| 'brand-strong'
	| 'brand-weak'
	| 'error'
	| 'error-strong'
	| 'error-weak'
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak';

/**
 * Foreground color variants for content text and icons.
 */
export type ContentForegroundColor =
	| 'caution'
	| 'caution-weak'
	| 'error'
	| 'error-weak'
	| 'info'
	| 'info-weak'
	| 'neutral'
	| 'neutral-weak'
	| 'success'
	| 'success-weak'
	| 'warning'
	| 'warning-weak';

/**
 * Foreground color variants for interactive element text and icons.
 */
export type InteractiveForegroundColor =
	| 'brand'
	| 'brand-strong'
	| 'error'
	| 'error-strong'
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak';

/**
 * Stroke color variants for surface borders.
 */
export type SurfaceStrokeColor =
	| 'brand'
	| 'brand-strong'
	| 'error'
	| 'error-strong'
	| 'info'
	| 'info-strong'
	| 'neutral'
	| 'neutral-strong'
	| 'neutral-weak'
	| 'success'
	| 'success-strong'
	| 'warning'
	| 'warning-strong';

/**
 * Stroke color variants for interactive element borders.
 */
export type InteractiveStrokeColor =
	| 'brand'
	| 'error'
	| 'error-strong'
	| 'neutral'
	| 'neutral-strong';
