// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const memo: typeof import('@wordpress/element')['memo']
  const useCallback: typeof import('@wordpress/element')['useCallback']
  const useContext: typeof import('@wordpress/element')['useContext']
  const useEffect: typeof import('@wordpress/element')['useEffect']
  const useMemo: typeof import('@wordpress/element')['useMemo']
  const useRef: typeof import('@wordpress/element')['useRef']
  const useState: typeof import('@wordpress/element')['useState']
}
export {}
