/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "border-control": string;
  readonly "color-indicator-wrapper": string;
  readonly "dropdown": string;
  readonly "inner-wrapper": string;
  readonly "inner-wrapper-has-width": string;
  readonly "popover-controls": string;
  readonly "reset-button-wrapper": string;
  readonly "slider": string;
};
export = styles;

