/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "bleed-content": string;
  readonly "content": string;
  readonly "loading": string;
};
export = styles;

