/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
import { applyFilters } from '@wordpress/hooks';
import {
	arrowDown,
	arrowLeft,
	arrowRight,
	arrowUp,
	atSymbol,
	audio,
	box,
	brush,
	calendar,
	cancelCircleFilled,
	capturePhoto,
	captureVideo,
	category,
	chartBar,
	check,
	chevronDown,
	chevronLeft,
	chevronRight,
	chevronUp,
	chevronLeftSmall,
	chevronRightSmall,
	close,
	closeSmall,
	cloud,
	cloudUpload,
	code,
	cog,
	color,
	commentContent,
	commentAuthorAvatar,
	desktop,
	download,
	edit,
	external,
	file,
	gallery,
	help,
	helpFilled,
	image,
	info,
	link,
	lockOutline,
	media,
	megaphone,
	mobile,
	page,
	people,
	plugins,
	plus,
	quote,
	redo,
	resizeCornerNE,
	rss,
	search,
	seen,
	settings,
	starEmpty,
	starFilled,
	store,
	trash,
	trendingDown,
	trendingUp,
	undo,
	video,
	warning,
	wordpress,
} from '@wordpress/icons';

const wordpressIcons = [
	{
		name: 'arrowDown',
		title: __( 'Arrow Down' ),
		icon: arrowDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowLeft',
		title: __( 'Arrow Left' ),
		icon: arrowLeft,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowRight',
		title: __( 'Arrow Right' ),
		icon: arrowRight,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowUp',
		title: __( 'Arrow Up' ),
		icon: arrowUp,
		categories: [ 'arrows' ],
	},
	{
		name: 'atSymbol',
		title: __( 'At Symbol' ),
		icon: atSymbol,
	},
	{
		name: 'audio',
		title: __( 'Audio' ),
		icon: audio,
		categories: [ 'blocks' ],
	},
	{
		name: 'box',
		title: __( 'Box' ),
		icon: box,
	},
	{
		name: 'brush',
		title: __( 'Brush' ),
		icon: brush,
	},
	{
		name: 'calendar',
		title: __( 'Calendar' ),
		icon: calendar,
	},
	{
		name: 'cancelCircleFilled',
		title: __( 'Cancel - Circle Filled' ),
		icon: cancelCircleFilled,
	},
	{
		name: 'capturePhoto',
		title: __( 'Capture Photo' ),
		icon: capturePhoto,
		categories: [ 'media' ],
	},
	{
		name: 'captureVideo',
		title: __( 'Capture Video' ),
		icon: captureVideo,
		categories: [ 'media' ],
	},
	{
		name: 'category',
		title: __( 'Category' ),
		icon: category,
		categories: [ 'admin' ],
	},
	{
		name: 'chartBar',
		title: __( 'Chart Bar' ),
		icon: chartBar,
	},
	{
		name: 'check',
		title: __( 'Check' ),
		icon: check,
	},
	{
		name: 'chevronDown',
		title: __( 'Chevron Down' ),
		icon: chevronDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronLeft',
		title: __( 'Chevron Left' ),
		icon: chevronLeft,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronRight',
		title: __( 'Chevron Right' ),
		icon: chevronRight,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronUp',
		title: __( 'Chevron Up' ),
		icon: chevronUp,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronLeftSmall',
		title: __( 'Chevron Left Small' ),
		icon: chevronLeftSmall,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronRightSmall',
		title: __( 'Chevron Right Small' ),
		icon: chevronRightSmall,
		categories: [ 'arrows' ],
	},
	{
		name: 'close',
		title: __( 'Close' ),
		icon: close,
	},
	{
		name: 'closeSmall',
		title: __( 'Close - Small' ),
		icon: closeSmall,
	},
	{
		name: 'cloud',
		title: __( 'Cloud' ),
		icon: cloud,
	},
	{
		name: 'cloudUpload',
		title: __( 'Cloud Upload' ),
		icon: cloudUpload,
		categories: [ 'media' ],
	},
	{
		name: 'code',
		title: __( 'Code' ),
		icon: code,
		categories: [ 'blocks' ],
	},
	{
		name: 'cog',
		title: __( 'Cog' ),
		icon: cog,
	},
	{
		name: 'color',
		title: __( 'Color' ),
		icon: color,
	},
	{
		name: 'commentContent',
		title: __( 'Comment Content' ),
		icon: commentContent,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentAuthorAvatar',
		title: __( 'Comment Author Avatar' ),
		icon: commentAuthorAvatar,
		categories: [ 'blocks' ],
	},
	{
		name: 'desktop',
		title: __( 'Desktop' ),
		icon: desktop,
		categories: [ 'design' ],
	},
	{
		name: 'download',
		title: __( 'Download' ),
		icon: download,
		categories: [ 'media' ],
	},
	{
		name: 'edit',
		title: __( 'Edit' ),
		icon: edit,
	},
	{
		name: 'external',
		title: __( 'External' ),
		icon: external,
	},
	{
		name: 'file',
		title: __( 'File' ),
		icon: file,
	},
	{
		name: 'gallery',
		title: __( 'Gallery' ),
		icon: gallery,
		categories: [ 'blocks' ],
	},
	{
		name: 'help',
		title: __( 'Help' ),
		icon: help,
	},
	{
		name: 'helpFilled',
		title: __( 'Help - Filled' ),
		icon: helpFilled,
	},
	{
		name: 'image',
		title: __( 'Image' ),
		icon: image,
		categories: [ 'blocks' ],
	},
	{
		name: 'info',
		title: __( 'Info' ),
		icon: info,
	},
	{
		name: 'link',
		title: __( 'Link' ),
		icon: link,
	},
	{
		name: 'lockOutline',
		title: __( 'Lock - Outline' ),
		icon: lockOutline,
	},
	{
		name: 'media',
		title: __( 'Media' ),
		icon: media,
		categories: [ 'blocks' ],
	},
	{
		name: 'megaphone',
		title: __( 'Megaphone' ),
		icon: megaphone,
	},
	{
		name: 'mobile',
		title: __( 'Mobile' ),
		icon: mobile,
		categories: [ 'design' ],
	},
	{
		name: 'page',
		title: __( 'Page' ),
		icon: page,
		categories: [ 'blocks' ],
	},
	{
		name: 'people',
		title: __( 'People' ),
		icon: people,
	},
	{
		name: 'plugins',
		title: __( 'Plugins' ),
		icon: plugins,
	},
	{
		name: 'plus',
		title: __( 'Plus' ),
		icon: plus,
	},
	{
		name: 'quote',
		title: __( 'Quote' ),
		icon: quote,
		categories: [ 'blocks' ],
	},
	{
		name: 'redo',
		title: __( 'Redo' ),
		icon: redo,
	},
	{
		name: 'resizeCornerNE',
		title: __( 'Resize Corner - Northeast' ),
		icon: resizeCornerNE,
	},
	{
		name: 'rss',
		title: __( 'RSS' ),
		icon: rss,
		categories: [ 'blocks' ],
	},
	{
		name: 'search',
		title: __( 'Search' ),
		icon: search,
		categories: [ 'blocks' ],
	},
	{
		name: 'seen',
		title: __( 'Seen' ),
		icon: seen,
	},
	{
		name: 'settings',
		title: __( 'Settings' ),
		icon: settings,
	},
	{
		name: 'starEmpty',
		title: __( 'Star - Empty' ),
		icon: starEmpty,
	},
	{
		name: 'starFilled',
		title: __( 'Star - Filled' ),
		icon: starFilled,
	},
	{
		name: 'store',
		title: __( 'Store' ),
		icon: store,
	},
	{
		name: 'trash',
		title: __( 'Trash' ),
		icon: trash,
	},
	{
		name: 'trendingDown',
		title: __( 'Trending Down' ),
		icon: trendingDown,
	},
	{
		name: 'trendingUp',
		title: __( 'Trending Up' ),
		icon: trendingUp,
	},
	{
		name: 'undo',
		title: __( 'Undo' ),
		icon: undo,
	},
	{
		name: 'video',
		title: __( 'Video' ),
		icon: video,
		categories: [ 'blocks' ],
	},
	{
		name: 'warning',
		title: __( 'Warning' ),
		icon: warning,
	},
	{
		name: 'wordpress',
		title: __( 'WordPress' ),
		icon: wordpress,
	},
];

const icons = [
	{
		isDefault: false,
		type: 'wordpress',
		title: __( 'WordPress' ),
		icons: [].concat( wordpressIcons ),
		categories: [
			{
				name: 'arrows',
				title: __( 'Arrows' ),
			},
			{
				name: 'blocks',
				title: __( 'Blocks' ),
			},
			{
				name: 'admin',
				title: __( 'Admin' ),
			},
			{
				name: 'design',
				title: __( 'Design' ),
			},
			{
				name: 'media',
				title: __( 'Media' ),
			},
		],
	},
];

export default function getIcons() {
	return applyFilters( 'blocks.registerBlockType.icons', icons );
}
