/**
 * @format
 * @flow
 */

export default {
	BLOCK: {
		UPDATE_ATTRIBUTES: 'UPDATE_BLOCK_ATTRIBUTES',
		FOCUS: 'BLOCK_FOCUS_ACTION',
		MOVE_UP: 'BLOCK_MOVE_UP_ACTION',
		MOVE_DOWN: 'BLOCK_MOVE_DOWN_ACTION',
		DELETE: 'BLOCK_DELETE_ACTION',
		CREATE: 'BLOCK_CREATE_ACTION',
	},
};
