/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "clone": string;
  readonly "invisible-drag-image": string;
  readonly "is-in-compat-slot": string;
};
export = styles;

