/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "actions": string;
  readonly "screen": string;
  readonly "title": string;
  readonly "title-icon": string;
};
export = styles;

