/*
 * This file is generated by the @wordpress/terrazzo-plugin-known-wpds-css-variables plugin.
 * Do not edit this file directly.
 */

export const tokens = {
	"--wpds-border-radius-xs": {
		"description": "Extra small radius",
		"group": "border"
	},
	"--wpds-border-radius-sm": {
		"description": "Small radius",
		"group": "border"
	},
	"--wpds-border-radius-md": {
		"description": "Medium radius",
		"group": "border"
	},
	"--wpds-border-radius-lg": {
		"description": "Large radius",
		"group": "border"
	},
	"--wpds-border-width-xs": {
		"description": "Extra small width",
		"group": "border"
	},
	"--wpds-border-width-sm": {
		"description": "Small width",
		"group": "border"
	},
	"--wpds-border-width-md": {
		"description": "Medium width",
		"group": "border"
	},
	"--wpds-border-width-lg": {
		"description": "Large width",
		"group": "border"
	},
	"--wpds-border-width-focus": {
		"description": "Border width for focus ring",
		"group": "border"
	},
	"--wpds-color-bg-surface-neutral": {
		"description": "Background color for surfaces with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-neutral-strong": {
		"description": "Background color for surfaces with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-neutral-weak": {
		"description": "Background color for surfaces with weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-brand": {
		"description": "Background color for surfaces with brand tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-success": {
		"description": "Background color for surfaces with success tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-success-weak": {
		"description": "Background color for surfaces with success tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-info": {
		"description": "Background color for surfaces with info tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-info-weak": {
		"description": "Background color for surfaces with info tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-warning": {
		"description": "Background color for surfaces with warning tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-warning-weak": {
		"description": "Background color for surfaces with warning tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-caution": {
		"description": "Background color for surfaces with caution tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-caution-weak": {
		"description": "Background color for surfaces with caution tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-error": {
		"description": "Background color for surfaces with error tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-surface-error-weak": {
		"description": "Background color for surfaces with error tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-strong": {
		"description": "Background color for interactive elements with neutral tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-strong-active": {
		"description": "Background color for interactive elements with neutral tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-strong-disabled": {
		"description": "Background color for interactive elements with neutral tone and strong emphasis, in their disabled state.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-weak": {
		"description": "Background color for interactive elements with neutral tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-weak-active": {
		"description": "Background color for interactive elements with neutral tone and weak emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-neutral-weak-disabled": {
		"description": "Background color for interactive elements with weak emphasis, in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-brand-strong": {
		"description": "Background color for interactive elements with brand tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-brand-strong-active": {
		"description": "Background color for interactive elements with brand tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-brand-weak": {
		"description": "Background color for interactive elements with brand tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-brand-weak-active": {
		"description": "Background color for interactive elements with brand tone and weak emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error": {
		"description": "Background color for interactive elements with error tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error-active": {
		"description": "Background color for interactive elements with error tone and normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error-strong": {
		"description": "Background color for interactive elements with error tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error-strong-active": {
		"description": "Background color for interactive elements with error tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error-weak": {
		"description": "Background color for interactive elements with error tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-bg-interactive-error-weak-active": {
		"description": "Background color for interactive elements with error tone and weak emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-track-neutral-weak": {
		"description": "Background color for tracks with a neutral tone and weak emphasis (eg. scrollbar track).",
		"group": "color"
	},
	"--wpds-color-bg-track-neutral": {
		"description": "Background color for tracks with a neutral tone and normal emphasis (eg. slider or progressbar track).",
		"group": "color"
	},
	"--wpds-color-bg-thumb-neutral-weak": {
		"description": "Background color for thumbs with a neutral tone and weak emphasis (eg. scrollbar thumb).",
		"group": "color"
	},
	"--wpds-color-bg-thumb-neutral-weak-active": {
		"description": "Background color for thumbs with a neutral tone and weak emphasis (eg. scrollbar thumb) that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-thumb-brand": {
		"description": "Background color for thumbs with a brand tone and normal emphasis (eg. slider thumb and filled track).",
		"group": "color"
	},
	"--wpds-color-bg-thumb-brand-active": {
		"description": "Background color for thumbs with a brand tone and normal emphasis (eg. slider thumb and filled track) that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-bg-thumb-neutral-disabled": {
		"description": "Background color for thumbs with normal emphasis (eg. slider thumb and filled track), in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-fg-content-neutral": {
		"description": "Foreground color for content like text with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-neutral-weak": {
		"description": "Foreground color for content like text with weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-success": {
		"description": "Foreground color for content like text with success tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-success-weak": {
		"description": "Foreground color for content like text with success tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-info": {
		"description": "Foreground color for content like text with info tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-info-weak": {
		"description": "Foreground color for content like text with info tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-warning": {
		"description": "Foreground color for content like text with warning tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-warning-weak": {
		"description": "Foreground color for content like text with warning tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-caution": {
		"description": "Foreground color for content like text with caution tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-caution-weak": {
		"description": "Foreground color for content like text with caution tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-error": {
		"description": "Foreground color for content like text with error tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-content-error-weak": {
		"description": "Foreground color for content like text with error tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral": {
		"description": "Foreground color for interactive elements with neutral tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-active": {
		"description": "Foreground color for interactive elements with neutral tone and normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-disabled": {
		"description": "Foreground color for interactive elements with normal emphasis, in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-strong": {
		"description": "Foreground color for interactive elements with neutral tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-strong-active": {
		"description": "Foreground color for interactive elements with neutral tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-strong-disabled": {
		"description": "Foreground color for interactive elements with strong emphasis, in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-weak": {
		"description": "Foreground color for interactive elements with neutral tone and weak emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-neutral-weak-disabled": {
		"description": "Foreground color for interactive elements with weak emphasis, in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-brand": {
		"description": "Foreground color for interactive elements with brand tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-brand-active": {
		"description": "Foreground color for interactive elements with brand tone and normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-brand-strong": {
		"description": "Foreground color for interactive elements with brand tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-brand-strong-active": {
		"description": "Foreground color for interactive elements with brand tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-error": {
		"description": "Foreground color for interactive elements with error tone and normal emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-error-active": {
		"description": "Foreground color for interactive elements with error tone and normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-error-strong": {
		"description": "Foreground color for interactive elements with error tone and strong emphasis.",
		"group": "color"
	},
	"--wpds-color-fg-interactive-error-strong-active": {
		"description": "Foreground color for interactive elements with error tone and strong emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-neutral": {
		"description": "Decorative stroke color used to define neutrally-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-neutral-weak": {
		"description": "Decorative stroke color used to define neutrally-toned surface boundaries with weak emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-neutral-strong": {
		"description": "Decorative stroke color used to define neutrally-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-brand": {
		"description": "Decorative stroke color used to define brand-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-brand-strong": {
		"description": "Decorative stroke color used to define brand-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-success": {
		"description": "Decorative stroke color used to define success-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-success-strong": {
		"description": "Decorative stroke color used to define success-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-info": {
		"description": "Decorative stroke color used to define info-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-info-strong": {
		"description": "Decorative stroke color used to define info-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-warning": {
		"description": "Decorative stroke color used to define warning-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-warning-strong": {
		"description": "Decorative stroke color used to define warning-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-error": {
		"description": "Decorative stroke color used to define error-toned surface boundaries with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-surface-error-strong": {
		"description": "Decorative stroke color used to define error-toned surface boundaries with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-neutral": {
		"description": "Accessible stroke color used for interactive neutrally-toned elements with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-neutral-active": {
		"description": "Accessible stroke color used for interactive neutrally-toned elements with normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-neutral-disabled": {
		"description": "Accessible stroke color used for interactive elements with normal emphasis, in their disabled state, regardless of the tone.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-neutral-strong": {
		"description": "Accessible stroke color used for interactive neutrally-toned elements with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-brand": {
		"description": "Accessible stroke color used for interactive brand-toned elements with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-brand-active": {
		"description": "Accessible stroke color used for interactive brand-toned elements with normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-error": {
		"description": "Accessible stroke color used for interactive error-toned elements with normal emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-error-active": {
		"description": "Accessible stroke color used for interactive error-toned elements with normal emphasis that are hovered, focused, or active.",
		"group": "color"
	},
	"--wpds-color-stroke-interactive-error-strong": {
		"description": "Accessible stroke color used for interactive error-toned elements with strong emphasis.",
		"group": "color"
	},
	"--wpds-color-stroke-focus-brand": {
		"description": "Accessible stroke color applied to focus rings.",
		"group": "color"
	},
	"--wpds-cursor-control": {
		"description": "Cursor style for interactive controls that are not links (e.g. buttons, checkboxes, and toggles).",
		"group": "cursor"
	},
	"--wpds-dimension-base": {
		"description": "Base dimension unit",
		"group": "dimension"
	},
	"--wpds-dimension-padding-xs": {
		"description": "Extra small padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-sm": {
		"description": "Small padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-md": {
		"description": "Medium padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-lg": {
		"description": "Large padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-xl": {
		"description": "Extra large padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-2xl": {
		"description": "2x extra large padding",
		"group": "dimension"
	},
	"--wpds-dimension-padding-3xl": {
		"description": "3x extra large padding",
		"group": "dimension"
	},
	"--wpds-dimension-gap-xs": {
		"description": "Extra small gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-sm": {
		"description": "Small gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-md": {
		"description": "Medium gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-lg": {
		"description": "Large gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-xl": {
		"description": "Extra large gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-2xl": {
		"description": "2x extra large gap",
		"group": "dimension"
	},
	"--wpds-dimension-gap-3xl": {
		"description": "3x extra large gap",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-xs": {
		"description": "Extra small surface width",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-sm": {
		"description": "Small surface width",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-md": {
		"description": "Medium surface width",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-lg": {
		"description": "Large surface width",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-xl": {
		"description": "Extra large surface width",
		"group": "dimension"
	},
	"--wpds-dimension-surface-width-2xl": {
		"description": "2x extra large surface width",
		"group": "dimension"
	},
	"--wpds-elevation-xs": {
		"description": "For sections and containers that group related content and controls, which may overlap other content. Example: Preview Frame.",
		"group": "elevation"
	},
	"--wpds-elevation-sm": {
		"description": "For components that provide contextual feedback without being intrusive. Generally non-interruptive. Example: Tooltips, Snackbar.",
		"group": "elevation"
	},
	"--wpds-elevation-md": {
		"description": "For components that offer additional actions. Example: Menus, Command Palette",
		"group": "elevation"
	},
	"--wpds-elevation-lg": {
		"description": "For components that confirm decisions or handle necessary interruptions. Example: Modals.",
		"group": "elevation"
	},
	"--wpds-font-family-heading": {
		"description": "Headings font family",
		"group": "typography"
	},
	"--wpds-font-family-body": {
		"description": "Body font family",
		"group": "typography"
	},
	"--wpds-font-family-mono": {
		"description": "Monospace font family",
		"group": "typography"
	},
	"--wpds-font-size-xs": {
		"description": "Extra small font size",
		"group": "typography"
	},
	"--wpds-font-size-sm": {
		"description": "Small font size",
		"group": "typography"
	},
	"--wpds-font-size-md": {
		"description": "Medium font size",
		"group": "typography"
	},
	"--wpds-font-size-lg": {
		"description": "Large font size",
		"group": "typography"
	},
	"--wpds-font-size-xl": {
		"description": "Extra large font size",
		"group": "typography"
	},
	"--wpds-font-size-2xl": {
		"description": "2X large font size",
		"group": "typography"
	},
	"--wpds-font-line-height-xs": {
		"description": "Extra small line height",
		"group": "typography"
	},
	"--wpds-font-line-height-sm": {
		"description": "Small line height",
		"group": "typography"
	},
	"--wpds-font-line-height-md": {
		"description": "Medium line height",
		"group": "typography"
	},
	"--wpds-font-line-height-lg": {
		"description": "Large line height",
		"group": "typography"
	},
	"--wpds-font-line-height-xl": {
		"description": "Extra large line height",
		"group": "typography"
	},
	"--wpds-font-line-height-2xl": {
		"description": "2X large line height",
		"group": "typography"
	},
	"--wpds-font-weight-regular": {
		"description": "Regular font weight for body text",
		"group": "typography"
	},
	"--wpds-font-weight-medium": {
		"description": "Medium font weight for emphasis and headings",
		"group": "typography"
	}
};

export const groups = {
	"border": [
		"--wpds-border-radius-xs",
		"--wpds-border-radius-sm",
		"--wpds-border-radius-md",
		"--wpds-border-radius-lg",
		"--wpds-border-width-xs",
		"--wpds-border-width-sm",
		"--wpds-border-width-md",
		"--wpds-border-width-lg",
		"--wpds-border-width-focus"
	],
	"color": [
		"--wpds-color-bg-surface-neutral",
		"--wpds-color-bg-surface-neutral-strong",
		"--wpds-color-bg-surface-neutral-weak",
		"--wpds-color-bg-surface-brand",
		"--wpds-color-bg-surface-success",
		"--wpds-color-bg-surface-success-weak",
		"--wpds-color-bg-surface-info",
		"--wpds-color-bg-surface-info-weak",
		"--wpds-color-bg-surface-warning",
		"--wpds-color-bg-surface-warning-weak",
		"--wpds-color-bg-surface-caution",
		"--wpds-color-bg-surface-caution-weak",
		"--wpds-color-bg-surface-error",
		"--wpds-color-bg-surface-error-weak",
		"--wpds-color-bg-interactive-neutral-strong",
		"--wpds-color-bg-interactive-neutral-strong-active",
		"--wpds-color-bg-interactive-neutral-strong-disabled",
		"--wpds-color-bg-interactive-neutral-weak",
		"--wpds-color-bg-interactive-neutral-weak-active",
		"--wpds-color-bg-interactive-neutral-weak-disabled",
		"--wpds-color-bg-interactive-brand-strong",
		"--wpds-color-bg-interactive-brand-strong-active",
		"--wpds-color-bg-interactive-brand-weak",
		"--wpds-color-bg-interactive-brand-weak-active",
		"--wpds-color-bg-interactive-error",
		"--wpds-color-bg-interactive-error-active",
		"--wpds-color-bg-interactive-error-strong",
		"--wpds-color-bg-interactive-error-strong-active",
		"--wpds-color-bg-interactive-error-weak",
		"--wpds-color-bg-interactive-error-weak-active",
		"--wpds-color-bg-track-neutral-weak",
		"--wpds-color-bg-track-neutral",
		"--wpds-color-bg-thumb-neutral-weak",
		"--wpds-color-bg-thumb-neutral-weak-active",
		"--wpds-color-bg-thumb-brand",
		"--wpds-color-bg-thumb-brand-active",
		"--wpds-color-bg-thumb-neutral-disabled",
		"--wpds-color-fg-content-neutral",
		"--wpds-color-fg-content-neutral-weak",
		"--wpds-color-fg-content-success",
		"--wpds-color-fg-content-success-weak",
		"--wpds-color-fg-content-info",
		"--wpds-color-fg-content-info-weak",
		"--wpds-color-fg-content-warning",
		"--wpds-color-fg-content-warning-weak",
		"--wpds-color-fg-content-caution",
		"--wpds-color-fg-content-caution-weak",
		"--wpds-color-fg-content-error",
		"--wpds-color-fg-content-error-weak",
		"--wpds-color-fg-interactive-neutral",
		"--wpds-color-fg-interactive-neutral-active",
		"--wpds-color-fg-interactive-neutral-disabled",
		"--wpds-color-fg-interactive-neutral-strong",
		"--wpds-color-fg-interactive-neutral-strong-active",
		"--wpds-color-fg-interactive-neutral-strong-disabled",
		"--wpds-color-fg-interactive-neutral-weak",
		"--wpds-color-fg-interactive-neutral-weak-disabled",
		"--wpds-color-fg-interactive-brand",
		"--wpds-color-fg-interactive-brand-active",
		"--wpds-color-fg-interactive-brand-strong",
		"--wpds-color-fg-interactive-brand-strong-active",
		"--wpds-color-fg-interactive-error",
		"--wpds-color-fg-interactive-error-active",
		"--wpds-color-fg-interactive-error-strong",
		"--wpds-color-fg-interactive-error-strong-active",
		"--wpds-color-stroke-surface-neutral",
		"--wpds-color-stroke-surface-neutral-weak",
		"--wpds-color-stroke-surface-neutral-strong",
		"--wpds-color-stroke-surface-brand",
		"--wpds-color-stroke-surface-brand-strong",
		"--wpds-color-stroke-surface-success",
		"--wpds-color-stroke-surface-success-strong",
		"--wpds-color-stroke-surface-info",
		"--wpds-color-stroke-surface-info-strong",
		"--wpds-color-stroke-surface-warning",
		"--wpds-color-stroke-surface-warning-strong",
		"--wpds-color-stroke-surface-error",
		"--wpds-color-stroke-surface-error-strong",
		"--wpds-color-stroke-interactive-neutral",
		"--wpds-color-stroke-interactive-neutral-active",
		"--wpds-color-stroke-interactive-neutral-disabled",
		"--wpds-color-stroke-interactive-neutral-strong",
		"--wpds-color-stroke-interactive-brand",
		"--wpds-color-stroke-interactive-brand-active",
		"--wpds-color-stroke-interactive-error",
		"--wpds-color-stroke-interactive-error-active",
		"--wpds-color-stroke-interactive-error-strong",
		"--wpds-color-stroke-focus-brand"
	],
	"cursor": [
		"--wpds-cursor-control"
	],
	"dimension": [
		"--wpds-dimension-base",
		"--wpds-dimension-padding-xs",
		"--wpds-dimension-padding-sm",
		"--wpds-dimension-padding-md",
		"--wpds-dimension-padding-lg",
		"--wpds-dimension-padding-xl",
		"--wpds-dimension-padding-2xl",
		"--wpds-dimension-padding-3xl",
		"--wpds-dimension-gap-xs",
		"--wpds-dimension-gap-sm",
		"--wpds-dimension-gap-md",
		"--wpds-dimension-gap-lg",
		"--wpds-dimension-gap-xl",
		"--wpds-dimension-gap-2xl",
		"--wpds-dimension-gap-3xl",
		"--wpds-dimension-surface-width-xs",
		"--wpds-dimension-surface-width-sm",
		"--wpds-dimension-surface-width-md",
		"--wpds-dimension-surface-width-lg",
		"--wpds-dimension-surface-width-xl",
		"--wpds-dimension-surface-width-2xl"
	],
	"elevation": [
		"--wpds-elevation-xs",
		"--wpds-elevation-sm",
		"--wpds-elevation-md",
		"--wpds-elevation-lg"
	],
	"typography": [
		"--wpds-font-family-heading",
		"--wpds-font-family-body",
		"--wpds-font-family-mono",
		"--wpds-font-size-xs",
		"--wpds-font-size-sm",
		"--wpds-font-size-md",
		"--wpds-font-size-lg",
		"--wpds-font-size-xl",
		"--wpds-font-size-2xl",
		"--wpds-font-line-height-xs",
		"--wpds-font-line-height-sm",
		"--wpds-font-line-height-md",
		"--wpds-font-line-height-lg",
		"--wpds-font-line-height-xl",
		"--wpds-font-line-height-2xl",
		"--wpds-font-weight-regular",
		"--wpds-font-weight-medium"
	]
};
