<?php
/**
 * Compatibility shims for KSES (content filtering) for WordPress 7.2.
 *
 * @package gutenberg
 */

/**
 * Adds 'text-shadow' to the list of safe CSS properties.
 * This is needed for the typography text shadow block support.
 *
 * @param string[] $attr Array of allowed CSS attributes.
 * @return string[] Modified array of allowed CSS attributes.
 */
function gutenberg_add_text_shadow_to_safe_style_css( $attr ) {
	if ( ! in_array( 'text-shadow', $attr, true ) ) {
		$attr[] = 'text-shadow';
	}

	return $attr;
}
add_filter( 'safe_style_css', 'gutenberg_add_text_shadow_to_safe_style_css' );

/**
 * Adds background-clip and its vendor-prefixed companions to the list of safe
 * CSS properties.
 *
 * The {@see safecss_filter_attr()} function only keeps allowlisted CSS
 * properties. Without these entries the declarations generated by the
 * background clip block support are stripped, leaving the style engine with an
 * empty `css` string.
 *
 * @param string[] $attr Array of allowed CSS attributes.
 * @return string[] Modified array of allowed CSS attributes.
 */
function gutenberg_add_background_clip_to_safe_style_css( array $attr ): array {
	$background_clip_properties = array(
		'background-clip',
		'-webkit-background-clip',
		'-webkit-text-fill-color',
	);

	foreach ( $background_clip_properties as $property ) {
		if ( ! in_array( $property, $attr, true ) ) {
			$attr[] = $property;
		}
	}

	return $attr;
}
add_filter( 'safe_style_css', 'gutenberg_add_background_clip_to_safe_style_css' );

/**
 * Allow CSS colour functions such as rgba(), hsl() and color-mix() in inline
 * styles.
 *
 * Without this, {@see safecss_filter_attr()} strips any declaration whose value
 * uses a colour function, including box shadows, border colours and text colours
 * generated by the style engine. This replaces each colour function whose
 * contents are plain colour syntax, innermost first, and re-checks the
 * remainder. Anything else is checked exactly as before.
 *
 * @param bool   $allow_css       Whether the CSS is allowed.
 * @param string $css_test_string The CSS declaration to test.
 * @return bool Whether the CSS is allowed.
 */
function gutenberg_allow_css_color_functions( $allow_css, $css_test_string ) {
	if ( true === $allow_css ) {
		return $allow_css;
	}

	$color_function = '/(?<![\w-])(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch|color-mix|color|light-dark)\(([^()]*)\)/i';

	for ( $pass = 0; $pass < 32; $pass++ ) {
		$count = preg_match_all( $color_function, $css_test_string, $matches );

		if ( false === $count ) {
			return $allow_css;
		}

		if ( 0 === $count ) {
			return 0 === preg_match( '%[\\\(&=}]|/\*%', $css_test_string ) ? true : $allow_css;
		}

		foreach ( $matches[1] as $contents ) {
			if ( ! preg_match( '/^[a-z0-9%.,\/+\s-]*$/i', $contents ) ) {
				return $allow_css;
			}
		}

		$css_test_string = preg_replace( $color_function, '0', $css_test_string );

		if ( null === $css_test_string ) {
			return $allow_css;
		}
	}

	return $allow_css;
}
add_filter( 'safecss_filter_attr_allow_css', 'gutenberg_allow_css_color_functions', 10, 2 );
