/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-bordered": string;
  readonly "is-rounded": string;
  readonly "is-separated": string;
  readonly "is-size-large": string;
  readonly "is-size-medium": string;
  readonly "is-size-small": string;
  readonly "is-spaced-around": string;
  readonly "is-unstyled-button": string;
  readonly "is-unstyled-link": string;
  readonly "item": string;
  readonly "item-group": string;
  readonly "item-wrapper": string;
};
export = styles;

