/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "child": string;
  readonly "layered": string;
  readonly "z-stack": string;
};
export = styles;

