module.exports = {
  "rules": {
    "at-rule-empty-line-before": [ 2, "always", {
      except: ["blockless-group"],
      ignore: ["after-comment"],
    } ],
    "at-rule-no-vendor-prefix": 2,
    "block-closing-brace-newline-after": [ 2, "always" ],
    "block-closing-brace-newline-before": [ 2, "always" ],
    "block-opening-brace-newline-after": [ 2, "always" ],
    "block-opening-brace-space-before": [ 2, "always" ],
    "color-hex-case": [ 2, "lower" ],
    "color-hex-length": [ 2, "short" ],
    "color-no-invalid-hex": 2,
    "declaration-bang-space-after": [ 2, "never" ],
    "declaration-bang-space-before": [ 2, "always" ],
    "declaration-block-semicolon-newline-after": [ 2, "always" ],
    "declaration-block-semicolon-space-before": [ 2, "never" ],
    "declaration-colon-newline-after": [ 2, "always-multi-line" ],
    "declaration-colon-space-after": [ 2, "always" ],
    "declaration-colon-space-before": [ 2, "never" ],
    "function-calc-no-unspaced-operator": 2,
    "function-comma-space-after": [ 2, "always" ],
    "function-comma-space-before": [ 2, "never" ],
    "function-parentheses-space-inside": [ 2, "never" ],
    "function-space-after": [ 2, "always" ],
    "function-url-quotes": [ 2, "none" ],
    "indentation": [ 2, "tab" ],
    "media-feature-colon-space-after": [ 2, "always" ],
    "media-feature-colon-space-before": [ 2, "never" ],
    "media-feature-name-no-vendor-prefix": 2,
    "media-feature-range-operator-space-after": [ 2, "always" ],
    "media-feature-range-operator-space-before": [ 2, "always" ],
    "media-query-list-comma-newline-after": [ 2, "always-multi-line" ],
    "media-query-list-comma-space-after": [ 2, "always-single-line" ],
    "media-query-list-comma-space-before": [ 2, "never" ],
    "media-query-parentheses-space-inside": [ 2, "never" ],
    "no-eol-whitespace": 2,
    "no-missing-eof-newline": 2,
    "number-leading-zero": [ 2, "always" ],
    "number-no-trailing-zeros": 2,
    "number-zero-length-no-unit": 2,
    "property-no-vendor-prefix": 2,
    "rule-no-shorthand-property-overrides": 2,
    "rule-nested-empty-line-before": [ 2, "always" ],
    "rule-non-nested-empty-line-before": [ 2, "always" ],
    "rule-trailing-semicolon": [ 2, "always" ],
    "selector-combinator-space-after": [ 2, "always" ],
    "selector-combinator-space-before": [ 2, "always" ],
    "selector-list-comma-newline-after": [ 2, "always" ],
    "selector-list-comma-space-before": [ 2, "never" ],
    "selector-no-vendor-prefix": 2,
    "string-quotes": [ 2, "double" ],
    "value-list-comma-newline-after": [ 2, "always-multi-line" ],
    "value-list-comma-space-after": [ 2, "always-single-line" ],
    "value-list-comma-space-before": [ 2, "never" ],
    "value-no-vendor-prefix": 2,
  },
}
