/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-brand": string;
  readonly "is-neutral": string;
  readonly "is-unstyled": string;
  readonly "link": string;
  readonly "link-icon": string;
};
export = styles;

