/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "content": string;
  readonly "has-navigation": string;
  readonly "has-padding": string;
  readonly "header": string;
  readonly "header-actions": string;
  readonly "header-content": string;
  readonly "header-lockup": string;
  readonly "header-navigation": string;
  readonly "header-subtitle": string;
  readonly "header-title": string;
  readonly "header-visual": string;
  readonly "page": string;
  readonly "sidebar-toggle-slot": string;
};
export = styles;

