/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "content": string;
  readonly "content-inner": string;
  readonly "header": string;
  readonly "header-content": string;
  readonly "header-description": string;
  readonly "header-trigger": string;
  readonly "header-trigger-positioner": string;
  readonly "header-trigger-wrapper": string;
  readonly "heading-wrapper": string;
  readonly "overflow-visible": string;
};
export = styles;

