/**
 * Internal dependencies
 */
import type { RampResult } from './types';
import type { DEFAULT_SEED_COLORS } from './constants';

export const DEFAULT_RAMPS: Record<
	keyof typeof DEFAULT_SEED_COLORS,
	RampResult
> = {
	bg: {
		ramp: {
			surface2: { color: '#f8f8f8', warning: false },
			bgFill1: { color: '#555', warning: false },
			fgFill: { color: '#f0f0f0', warning: false },
			bgFill2: { color: '#474747', warning: false },
			surface6: { color: '#d0d0d0', warning: false },
			surface5: { color: '#dfdfdf', warning: false },
			surface4: { color: '#eaeaea', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#1e1e1e', warning: false },
			fgSurface3: { color: '#6c6c6c', warning: false },
			fgSurface2: { color: '#898989', warning: false },
			fgSurface1: { color: '#a9a9a9', warning: false },
			stroke3: { color: '#898989', warning: false },
			stroke4: { color: '#6a6a6a', warning: false },
			stroke2: { color: '#aeaeae', warning: false },
			stroke1: { color: '#d0d0d0', warning: false },
			bgFillDark: { color: '#1e1e1e', warning: false },
			fgFillDark: { color: '#f0f0f0', warning: false },
			bgFillInverted2: { color: '#1e1e1e', warning: false },
			bgFillInverted1: { color: '#2f2f2f', warning: false },
			fgFillInverted: { color: '#f0f0f0', warning: false },
			surface1: { color: '#efefef', warning: false },
		},
		direction: 'darker',
	},
	primary: {
		ramp: {
			bgFill1: { color: '#3858e9', warning: false },
			fgFill: { color: '#eff0f2', warning: false },
			bgFill2: { color: '#2c47d7', warning: false },
			surface2: { color: '#f6f8fc', warning: false },
			surface6: { color: '#c4d0ee', warning: false },
			surface5: { color: '#d7dff3', warning: false },
			surface4: { color: '#e5eaf7', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#080071', warning: false },
			fgSurface3: { color: '#3858e9', warning: false },
			fgSurface2: { color: '#577fff', warning: false },
			fgSurface1: { color: '#81a6ff', warning: false },
			stroke3: { color: '#3858e9', warning: false },
			stroke4: { color: '#2236c7', warning: false },
			stroke2: { color: '#7085c0', warning: false },
			stroke1: { color: '#93a4d0', warning: false },
			bgFillDark: { color: '#1b1e26', warning: false },
			fgFillDark: { color: '#eff0f2', warning: false },
			bgFillInverted2: { color: '#1b1e26', warning: false },
			bgFillInverted1: { color: '#1401a5', warning: false },
			fgFillInverted: { color: '#eff0f2', warning: false },
			surface1: { color: '#ecf0f9', warning: false },
		},
		direction: 'darker',
	},
	info: {
		ramp: {
			bgFill1: { color: '#0090ff', warning: false },
			fgFill: { color: '#1b1e23', warning: false },
			bgFill2: { color: '#007eec', warning: false },
			surface2: { color: '#f5f9fd', warning: false },
			surface6: { color: '#b9d3f0', warning: false },
			surface5: { color: '#d0e1f5', warning: false },
			surface4: { color: '#e0ecf8', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#001758', warning: false },
			fgSurface3: { color: '#006cd8', warning: false },
			fgSurface2: { color: '#008bf9', warning: false },
			fgSurface1: { color: '#4dafff', warning: false },
			stroke3: { color: '#006cd8', warning: false },
			stroke4: { color: '#004bb5', warning: false },
			stroke2: { color: '#5c90c9', warning: false },
			stroke1: { color: '#8baed6', warning: false },
			bgFillDark: { color: '#1b1e23', warning: false },
			fgFillDark: { color: '#eff0f2', warning: false },
			bgFillInverted2: { color: '#1b1e23', warning: false },
			bgFillInverted1: { color: '#00297b', warning: false },
			fgFillInverted: { color: '#eff0f2', warning: false },
			surface1: { color: '#e9f1fa', warning: false },
		},
		direction: 'darker',
	},
	success: {
		ramp: {
			bgFill1: { color: '#4ab866', warning: false },
			fgFill: { color: '#1b1f1c', warning: false },
			bgFill2: { color: '#34a554', warning: false },
			surface2: { color: '#f0fcf2', warning: false },
			surface6: { color: '#7be792', warning: false },
			surface5: { color: '#abf0b7', warning: false },
			surface4: { color: '#cdf5d2', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#002b00', warning: false },
			fgSurface3: { color: '#008030', warning: false },
			fgSurface2: { color: '#2a9e4d', warning: false },
			fgSurface1: { color: '#52bf6d', warning: false },
			stroke3: { color: '#008030', warning: false },
			stroke4: { color: '#006013', warning: false },
			stroke2: { color: '#629a6c', warning: false },
			stroke1: { color: '#78bb84', warning: false },
			bgFillDark: { color: '#1b1f1c', warning: false },
			fgFillDark: { color: '#edf2ed', warning: false },
			bgFillInverted2: { color: '#1b1f1c', warning: false },
			bgFillInverted1: { color: '#003b00', warning: false },
			fgFillInverted: { color: '#edf2ed', warning: false },
			surface1: { color: '#ddf8e1', warning: false },
		},
		direction: 'darker',
	},
	warning: {
		ramp: {
			bgFill1: { color: '#f0b849', warning: false },
			fgFill: { color: '#1f1e1b', warning: false },
			bgFill2: { color: '#dba32f', warning: false },
			surface2: { color: '#fdf7ee', warning: false },
			surface6: { color: '#f0cb89', warning: false },
			surface5: { color: '#f5dcb2', warning: false },
			surface4: { color: '#f8e8cd', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#2f1800', warning: false },
			fgSurface3: { color: '#966200', warning: false },
			fgSurface2: { color: '#b58000', warning: false },
			fgSurface1: { color: '#d7a02b', warning: false },
			stroke3: { color: '#966200', warning: false },
			stroke4: { color: '#724700', warning: false },
			stroke2: { color: '#a18a61', warning: false },
			stroke1: { color: '#c3a777', warning: false },
			bgFillDark: { color: '#1f1e1b', warning: false },
			fgFillDark: { color: '#f3f0e9', warning: false },
			bgFillInverted2: { color: '#1f1e1b', warning: false },
			bgFillInverted1: { color: '#472900', warning: false },
			fgFillInverted: { color: '#f3f0e9', warning: false },
			surface1: { color: '#faefdc', warning: false },
		},
		direction: 'darker',
	},
	error: {
		ramp: {
			bgFill1: { color: '#cc1818', warning: false },
			fgFill: { color: '#f2efef', warning: false },
			bgFill2: { color: '#b90000', warning: false },
			surface2: { color: '#fdf6f5', warning: false },
			surface6: { color: '#f5c5bd', warning: false },
			surface5: { color: '#f8d8d3', warning: false },
			surface4: { color: '#fae5e2', warning: false },
			surface3: { color: '#fff', warning: false },
			fgSurface4: { color: '#4a0000', warning: false },
			fgSurface3: { color: '#cc1818', warning: false },
			fgSurface2: { color: '#f64b40', warning: false },
			fgSurface1: { color: '#ff8070', warning: false },
			stroke3: { color: '#cc1818', warning: false },
			stroke4: { color: '#a30000', warning: false },
			stroke2: { color: '#cd695d', warning: false },
			stroke1: { color: '#dc9085', warning: false },
			bgFillDark: { color: '#231c1b', warning: false },
			fgFillDark: { color: '#f2efef', warning: false },
			bgFillInverted2: { color: '#231c1b', warning: false },
			bgFillInverted1: { color: '#6d0000', warning: false },
			fgFillInverted: { color: '#f2efef', warning: false },
			surface1: { color: '#fcedea', warning: false },
		},
		direction: 'darker',
	},
};
