/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "badge": string;
  readonly "is-draft-intent": string;
  readonly "is-high-intent": string;
  readonly "is-informational-intent": string;
  readonly "is-low-intent": string;
  readonly "is-medium-intent": string;
  readonly "is-none-intent": string;
  readonly "is-stable-intent": string;
};
export = styles;

