/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "has-border": string;
  readonly "has-enclosing-borders": string;
  readonly "is-block": string;
  readonly "toggle-group-control": string;
};
export = styles;

