/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "dropdown-motion": string;
  readonly "dropdown-motion--fade-only": string;
};
export = styles;

