/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "description": string;
  readonly "is-plain": string;
  readonly "label": string;
};
export = styles;

