/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "outset-ring--focus": string;
  readonly "outset-ring--focus-except-active": string;
  readonly "outset-ring--focus-parent-visible": string;
  readonly "outset-ring--focus-visible": string;
  readonly "outset-ring--focus-within": string;
  readonly "outset-ring--focus-within-except-active": string;
  readonly "outset-ring--focus-within-visible": string;
};
export = styles;

