/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "a": string;
  readonly "button": string;
  readonly "div": string;
  readonly "heading": string;
  readonly "input": string;
  readonly "p": string;
  readonly "textarea": string;
};
export = styles;

