/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "empty": string;
  readonly "group": string;
  readonly "group-label": string;
  readonly "is-size-small": string;
  readonly "item": string;
  readonly "item-icon": string;
  readonly "item-indicator-icon": string;
  readonly "list": string;
  readonly "list-footer": string;
  readonly "list-scrollable-container": string;
  readonly "popup": string;
};
export = styles;

