/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "content": string;
  readonly "footer": string;
  readonly "header": string;
  readonly "title": string;
};
export = styles;

