/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-minimal": string;
  readonly "trigger": string;
  readonly "trigger-caret": string;
  readonly "trigger-value": string;
  readonly "trigger-wrapper": string;
};
export = styles;

