/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "dropdown-area": string;
  readonly "dropdown-popup": string;
  readonly "inline-controls": string;
  readonly "persistent-controls": string;
};
export = styles;

