/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "pulse": string;
  readonly "skeleton": string;
  readonly "skeleton-pulse": string;
};
export = styles;

