/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "error-message": string;
  readonly "footer-column": string;
  readonly "irreversible-action": string;
};
export = styles;

