/**
 * Internal dependencies
 */
import './style.scss';
import { Dashicon } from '../';

function TinymceIcon( { icon, ...props } ) {
	const Tiny2Dash = {
		save: '',
		newdocument: 'media-default',
		fullpage: 'editor-expand',
		alignleft: 'editor-alignleft',
		aligncenter: 'editor-aligncenter',
		alignright: 'editor-alignright',
		alignjustify: 'editor-justify',
		alignnone: '',
		cut: '',
		paste: '',
		searchreplace: '',
		bullist: 'editor-ul',
		numlist: 'editor-ol',
		indent: 'editor-indent',
		outdent: 'editor-outdent',
		blockquote: 'editor-quote',
		undo: 'undo',
		redo: 'redo',
		link: 'admin-links',
		unlink: 'editor-unlink',
		anchor: 'sticky',
		image: 'format-image',
		media: 'admin-media',
		help: 'editor-help',
		code: 'editor-code',
		insertdatetime: 'clock',
		preview: '',
		forecolor: 'editor-textcolor',
		backcolor: '',
		table: 'editor-table',
		hr: 'minus',
		removeformat: 'editor-removeformatting',
		subscript: '',
		superscript: '',
		charmap: 'editor-customchar',
		emoticons: 'smiley',
		print: '',
		fullscreen: 'editor-expand',
		spellchecker: 'editor-spellcheck',
		nonbreaking: '',
		template: '',
		pagebreak: 'admin-page',
		restoredraft: '',
		bold: 'editor-bold',
		italic: 'editor-italic',
		underline: 'editor-underline',
		strikethrough: 'editor-strikethrough',
		visualchars: '',
		visualblocks: 'editor-paragraph',
		ltr: '',
		rtl: 'editor-rtl',
		copy: '',
		resize: '',
		browse: 'search',
		pastetext: 'editor-paste-text',
		rotateleft: 'image-rotate-left',
		rotateright: 'image-rotate-right',
		crop: 'image-crop',
		editimage: '',
		options: 'admin-generic',
		flipv: 'image-flip-vertical',
		fliph: 'image-flip-horizontal',
		zoomin: '',
		zoomout: '',
		sun: '',
		moon: '',
		arrowleft: 'arrow-left-alt',
		arrowright: 'arrow-right-alt',
		drop: '',
		contrast: '',
		sharpen: '',
		resize2: '',
		orientation: '',
		invert: '',
		gamma: '',
		remove: 'trash',
		tablerowprops: '',
		tablecellprops: '',
		table2: '',
		tablemergecells: '',
		tableinsertcolbefore: '',
		tableinsertcolafter: '',
		tableinsertrowbefore: '',
		tableinsertrowafter: '',
		tablesplitcells: '',
		tabledelete: '',
		tableleftheader: '',
		tabletopheader: '',
		tabledeleterow: '',
		tabledeletecol: '',
		codesample: '',
		fill: '',
		borderwidth: '',
		line: '',
		count: '',
		translate: 'translation',
		drag: '',
		home: 'admin-home',
		upload: 'upload',
		bubble: '',
		user: 'admin-users',
		lock: 'lock',
		unlock: 'unlock',
		settings: 'admin-settings',
		remove2: 'no-alt',
		menu: 'menu',
		warning: 'warning',
		question: '',
		pluscircle: 'plus-alt',
		info: 'info',
		notice: '',
		arrowup: 'arrow-up-alt',
		arrowdown: 'arrow-down-alt',
		arrowup2: 'arrow-up',
		arrowdown2: 'arrow-down',
		menu2: '',
		newtab: '',
		a11y: 'universal-access',
		plus: 'plus',
		insert: '',
		minus: 'minus',
		books: 'book',
		reload: 'image-rotate',
		toc: '',
		checkmark: '',
		checkbox: 'yes',
		selected: 'yes',
	};

	if ( Tiny2Dash[ icon ] ) {
		return <Dashicon icon={ Tiny2Dash[ icon ] } { ...props } />;
	}

	return <i className={ `mce-ico mce-i-${ icon }` } />;
}

export default TinymceIcon;
