/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "feedIcon": string;
  readonly "meta": string;
  readonly "root": string;
  readonly "titleLink": string;
};
export = styles;

