/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "canvas": string;
  readonly "components-snackbar": string;
  readonly "has-canvas": string;
  readonly "has-full-canvas": string;
  readonly "has-mobile-drawer": string;
  readonly "inspector": string;
  readonly "is-mobile": string;
  readonly "layout": string;
  readonly "layout-single-page": string;
  readonly "mobile-sidebar-drawer": string;
  readonly "notices-snackbar": string;
  readonly "sidebar": string;
  readonly "sidebar-backdrop": string;
  readonly "stage": string;
  readonly "surfaces": string;
};
export = styles;

