/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "canvas": string;
  readonly "inspector": string;
  readonly "layout": string;
  readonly "slideFromRight": string;
  readonly "slideHeaderFromTop": string;
  readonly "slideHeaderToTop": string;
  readonly "slideSidebarFromRight": string;
  readonly "slideSidebarToRight": string;
  readonly "slideToRight": string;
  readonly "stage": string;
  readonly "zoomIn": string;
  readonly "zoomOut": string;
};
export = styles;

