/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "scroll-auto": string;
  readonly "scroll-x": string;
  readonly "scroll-y": string;
  readonly "scrollable": string;
  readonly "smooth-scroll": string;
};
export = styles;

