/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "default-controls-item": string;
  readonly "dropdown-menu": string;
  readonly "reset-label": string;
  readonly "tools-panel": string;
  readonly "tools-panel-header": string;
  readonly "tools-panel-heading": string;
  readonly "tools-panel-hidden-inner-wrapper": string;
  readonly "tools-panel-item": string;
  readonly "tools-panel-item-placeholder": string;
  readonly "tools-panel-with-inner-wrapper": string;
};
export = styles;

