/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "caption-after-enter": string;
  readonly "caption-after-exit": string;
  readonly "caption-before-enter": string;
  readonly "caption-before-exit": string;
  readonly "caption-label": string;
  readonly "day": string;
  readonly "day-button": string;
  readonly "fade-in": string;
  readonly "fade-out": string;
  readonly "hidden": string;
  readonly "month-caption": string;
  readonly "month-grid": string;
  readonly "months": string;
  readonly "nav": string;
  readonly "nav-button": string;
  readonly "outside": string;
  readonly "preview": string;
  readonly "range-end": string;
  readonly "range-middle": string;
  readonly "range-start": string;
  readonly "root": string;
  readonly "selected": string;
  readonly "slide-in-left": string;
  readonly "slide-in-right": string;
  readonly "slide-out-left": string;
  readonly "slide-out-right": string;
  readonly "today": string;
  readonly "weekday": string;
  readonly "weeks-after-enter": string;
  readonly "weeks-after-exit": string;
  readonly "weeks-before-enter": string;
  readonly "weeks-before-exit": string;
};
export = styles;

