<?php
// This file is automatically generated. Do not edit directly.
if ( ! defined( 'ABSPATH' ) ) {
	die( 'Silence is golden.' );
}

return array(
	'arrow-down-left'     => array(
		'label'    => _x( 'Arrow Down Left', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-down-left.svg',
	),
	'arrow-down-right'    => array(
		'label'    => _x( 'Arrow Down Right', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-down-right.svg',
	),
	'arrow-down'          => array(
		'label'    => _x( 'Arrow Down', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-down.svg',
	),
	'arrow-left'          => array(
		'label'    => _x( 'Arrow Left', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-left.svg',
	),
	'arrow-right'         => array(
		'label'    => _x( 'Arrow Right', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-right.svg',
	),
	'arrow-up-left'       => array(
		'label'    => _x( 'Arrow Up Left', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-up-left.svg',
	),
	'arrow-up-right'      => array(
		'label'    => _x( 'Arrow Up Right', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-up-right.svg',
	),
	'arrow-up'            => array(
		'label'    => _x( 'Arrow Up', 'icon label', 'gutenberg' ),
		'filePath' => 'library/arrow-up.svg',
	),
	'at-symbol'           => array(
		'label'    => _x( 'At Symbol (@)', 'icon label', 'gutenberg' ),
		'filePath' => 'library/at-symbol.svg',
	),
	'audio'               => array(
		'label'    => _x( 'Audio', 'icon label', 'gutenberg' ),
		'filePath' => 'library/audio.svg',
	),
	'bell'                => array(
		'label'    => _x( 'Bell', 'icon label', 'gutenberg' ),
		'filePath' => 'library/bell.svg',
	),
	'block-default'       => array(
		'label'    => _x( 'Block Default', 'icon label', 'gutenberg' ),
		'filePath' => 'library/block-default.svg',
	),
	'block-meta'          => array(
		'label'    => _x( 'Block Meta', 'icon label', 'gutenberg' ),
		'filePath' => 'library/block-meta.svg',
	),
	'block-table'         => array(
		'label'    => _x( 'Block Table', 'icon label', 'gutenberg' ),
		'filePath' => 'library/block-table.svg',
	),
	'calendar'            => array(
		'label'    => _x( 'Calendar', 'icon label', 'gutenberg' ),
		'filePath' => 'library/calendar.svg',
	),
	'capture-photo'       => array(
		'label'    => _x( 'Capture Photo', 'icon label', 'gutenberg' ),
		'filePath' => 'library/capture-photo.svg',
	),
	'capture-video'       => array(
		'label'    => _x( 'Capture Video', 'icon label', 'gutenberg' ),
		'filePath' => 'library/capture-video.svg',
	),
	'cart'                => array(
		'label'    => _x( 'Cart', 'icon label', 'gutenberg' ),
		'filePath' => 'library/cart.svg',
	),
	'category'            => array(
		'label'    => _x( 'Category', 'icon label', 'gutenberg' ),
		'filePath' => 'library/category.svg',
	),
	'caution'             => array(
		'label'    => _x( 'Caution', 'icon label', 'gutenberg' ),
		'filePath' => 'library/caution.svg',
	),
	'chart-bar'           => array(
		'label'    => _x( 'Chart Bar', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chart-bar.svg',
	),
	'check'               => array(
		'label'    => _x( 'Check', 'icon label', 'gutenberg' ),
		'filePath' => 'library/check.svg',
	),
	'chevron-down'        => array(
		'label'    => _x( 'Chevron Down', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-down.svg',
	),
	'chevron-down-small'  => array(
		'label'    => _x( 'Chevron Down Small', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-down-small.svg',
	),
	'chevron-left'        => array(
		'label'    => _x( 'Chevron Left', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-left.svg',
	),
	'chevron-left-small'  => array(
		'label'    => _x( 'Chevron Left Small', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-left-small.svg',
	),
	'chevron-right'       => array(
		'label'    => _x( 'Chevron Right', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-right.svg',
	),
	'chevron-right-small' => array(
		'label'    => _x( 'Chevron Right Small', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-right-small.svg',
	),
	'chevron-up'          => array(
		'label'    => _x( 'Chevron Up', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-up.svg',
	),
	'chevron-up-down'     => array(
		'label'    => _x( 'Chevron Up Down', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-up-down.svg',
	),
	'chevron-up-small'    => array(
		'label'    => _x( 'Chevron Up Small', 'icon label', 'gutenberg' ),
		'filePath' => 'library/chevron-up-small.svg',
	),
	'comment'             => array(
		'label'    => _x( 'Comment', 'icon label', 'gutenberg' ),
		'filePath' => 'library/comment.svg',
	),
	'cover'               => array(
		'label'    => _x( 'Cover', 'icon label', 'gutenberg' ),
		'filePath' => 'library/cover.svg',
	),
	'create'              => array(
		'label'    => _x( 'Create', 'icon label', 'gutenberg' ),
		'filePath' => 'library/create.svg',
	),
	'desktop'             => array(
		'label'    => _x( 'Desktop', 'icon label', 'gutenberg' ),
		'filePath' => 'library/desktop.svg',
	),
	'download'            => array(
		'label'    => _x( 'Download', 'icon label', 'gutenberg' ),
		'filePath' => 'library/download.svg',
	),
	'drawer-left'         => array(
		'label'    => _x( 'Drawer Left', 'icon label', 'gutenberg' ),
		'filePath' => 'library/drawer-left.svg',
	),
	'drawer-right'        => array(
		'label'    => _x( 'Drawer Right', 'icon label', 'gutenberg' ),
		'filePath' => 'library/drawer-right.svg',
	),
	'envelope'            => array(
		'label'    => _x( 'Envelope', 'icon label', 'gutenberg' ),
		'filePath' => 'library/envelope.svg',
	),
	'error'               => array(
		'label'    => _x( 'Error', 'icon label', 'gutenberg' ),
		'filePath' => 'library/error.svg',
	),
	'external'            => array(
		'label'    => _x( 'External', 'icon label', 'gutenberg' ),
		'filePath' => 'library/external.svg',
	),
	'file'                => array(
		'label'    => _x( 'File', 'icon label', 'gutenberg' ),
		'filePath' => 'library/file.svg',
	),
	'gallery'             => array(
		'label'    => _x( 'Gallery', 'icon label', 'gutenberg' ),
		'filePath' => 'library/gallery.svg',
	),
	'group'               => array(
		'label'    => _x( 'Group', 'icon label', 'gutenberg' ),
		'filePath' => 'library/group.svg',
	),
	'heading'             => array(
		'label'    => _x( 'Heading', 'icon label', 'gutenberg' ),
		'filePath' => 'library/heading.svg',
	),
	'help'                => array(
		'label'    => _x( 'Help', 'icon label', 'gutenberg' ),
		'filePath' => 'library/help.svg',
	),
	'home'                => array(
		'label'    => _x( 'Home', 'icon label', 'gutenberg' ),
		'filePath' => 'library/home.svg',
	),
	'image'               => array(
		'label'    => _x( 'Image', 'icon label', 'gutenberg' ),
		'filePath' => 'library/image.svg',
	),
	'info'                => array(
		'label'    => _x( 'Info', 'icon label', 'gutenberg' ),
		'filePath' => 'library/info.svg',
	),
	'key'                 => array(
		'label'    => _x( 'Key', 'icon label', 'gutenberg' ),
		'filePath' => 'library/key.svg',
	),
	'language'            => array(
		'label'    => _x( 'Language', 'icon label', 'gutenberg' ),
		'filePath' => 'library/language.svg',
	),
	'map-marker'          => array(
		'label'    => _x( 'Map Marker', 'icon label', 'gutenberg' ),
		'filePath' => 'library/map-marker.svg',
	),
	'menu'                => array(
		'label'    => _x( 'Menu', 'icon label', 'gutenberg' ),
		'filePath' => 'library/menu.svg',
	),
	'mobile'              => array(
		'label'    => _x( 'Mobile', 'icon label', 'gutenberg' ),
		'filePath' => 'library/mobile.svg',
	),
	'more-horizontal'     => array(
		'label'    => _x( 'More Horizontal', 'icon label', 'gutenberg' ),
		'filePath' => 'library/more-horizontal.svg',
	),
	'more-vertical'       => array(
		'label'    => _x( 'More Vertical', 'icon label', 'gutenberg' ),
		'filePath' => 'library/more-vertical.svg',
	),
	'next'                => array(
		'label'    => _x( 'Next', 'icon label', 'gutenberg' ),
		'filePath' => 'library/next.svg',
	),
	'paragraph'           => array(
		'label'    => _x( 'Paragraph', 'icon label', 'gutenberg' ),
		'filePath' => 'library/paragraph.svg',
	),
	'payment'             => array(
		'label'    => _x( 'Payment', 'icon label', 'gutenberg' ),
		'filePath' => 'library/payment.svg',
	),
	'pencil'              => array(
		'label'    => _x( 'Pencil', 'icon label', 'gutenberg' ),
		'filePath' => 'library/pencil.svg',
	),
	'people'              => array(
		'label'    => _x( 'People', 'icon label', 'gutenberg' ),
		'filePath' => 'library/people.svg',
	),
	'plus'                => array(
		'label'    => _x( 'Plus', 'icon label', 'gutenberg' ),
		'filePath' => 'library/plus.svg',
	),
	'plus-circle'         => array(
		'label'    => _x( 'Plus Circle', 'icon label', 'gutenberg' ),
		'filePath' => 'library/plus-circle.svg',
	),
	'previous'            => array(
		'label'    => _x( 'Previous', 'icon label', 'gutenberg' ),
		'filePath' => 'library/previous.svg',
	),
	'published'           => array(
		'label'    => _x( 'Published', 'icon label', 'gutenberg' ),
		'filePath' => 'library/published.svg',
	),
	'quote'               => array(
		'label'    => _x( 'Quote', 'icon label', 'gutenberg' ),
		'filePath' => 'library/quote.svg',
	),
	'receipt'             => array(
		'label'    => _x( 'Receipt', 'icon label', 'gutenberg' ),
		'filePath' => 'library/receipt.svg',
	),
	'rss'                 => array(
		'label'    => _x( 'RSS', 'icon label', 'gutenberg' ),
		'filePath' => 'library/rss.svg',
	),
	'scheduled'           => array(
		'label'    => _x( 'Scheduled', 'icon label', 'gutenberg' ),
		'filePath' => 'library/scheduled.svg',
	),
	'search'              => array(
		'label'    => _x( 'Search', 'icon label', 'gutenberg' ),
		'filePath' => 'library/search.svg',
	),
	'settings'            => array(
		'label'    => _x( 'Settings', 'icon label', 'gutenberg' ),
		'filePath' => 'library/settings.svg',
	),
	'shadow'              => array(
		'label'    => _x( 'Shadow', 'icon label', 'gutenberg' ),
		'filePath' => 'library/shadow.svg',
	),
	'share'               => array(
		'label'    => _x( 'Share', 'icon label', 'gutenberg' ),
		'filePath' => 'library/share.svg',
	),
	'shield'              => array(
		'label'    => _x( 'Shield', 'icon label', 'gutenberg' ),
		'filePath' => 'library/shield.svg',
	),
	'shuffle'             => array(
		'label'    => _x( 'Shuffle', 'icon label', 'gutenberg' ),
		'filePath' => 'library/shuffle.svg',
	),
	'star-empty'          => array(
		'label'    => _x( 'Star Empty', 'icon label', 'gutenberg' ),
		'filePath' => 'library/star-empty.svg',
	),
	'star-filled'         => array(
		'label'    => _x( 'Star Filled', 'icon label', 'gutenberg' ),
		'filePath' => 'library/star-filled.svg',
	),
	'star-half'           => array(
		'label'    => _x( 'Star Half', 'icon label', 'gutenberg' ),
		'filePath' => 'library/star-half.svg',
	),
	'store'               => array(
		'label'    => _x( 'Store', 'icon label', 'gutenberg' ),
		'filePath' => 'library/store.svg',
	),
	'styles'              => array(
		'label'    => _x( 'Styles', 'icon label', 'gutenberg' ),
		'filePath' => 'library/styles.svg',
	),
	'symbol'              => array(
		'label'    => _x( 'Symbol', 'icon label', 'gutenberg' ),
		'filePath' => 'library/symbol.svg',
	),
	'symbol-filled'       => array(
		'label'    => _x( 'Symbol Filled', 'icon label', 'gutenberg' ),
		'filePath' => 'library/symbol-filled.svg',
	),
	'table'               => array(
		'label'    => _x( 'Table', 'icon label', 'gutenberg' ),
		'filePath' => 'library/table.svg',
	),
	'tablet'              => array(
		'label'    => _x( 'Tablet', 'icon label', 'gutenberg' ),
		'filePath' => 'library/tablet.svg',
	),
	'tag'                 => array(
		'label'    => _x( 'Tag', 'icon label', 'gutenberg' ),
		'filePath' => 'library/tag.svg',
	),
	'tip'                 => array(
		'label'    => _x( 'Tip', 'icon label', 'gutenberg' ),
		'filePath' => 'library/tip.svg',
	),
	'upload'              => array(
		'label'    => _x( 'Upload', 'icon label', 'gutenberg' ),
		'filePath' => 'library/upload.svg',
	),
	'verse'               => array(
		'label'    => _x( 'Verse', 'icon label', 'gutenberg' ),
		'filePath' => 'library/verse.svg',
	),
);
