/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "cell": string;
  readonly "grid-container": string;
  readonly "grid-row": string;
  readonly "point": string;
};
export = styles;

