/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "compact-actions": string;
  readonly "icon-action": string;
  readonly "prefixed-action": string;
  readonly "widget-footer": string;
};
export = styles;

