name: 'Setup Node'
description: 'Setup node and install dependencies with caching support'
inputs:
    node-version:
        description: 'Optional node version to pass to setup-node'
        required: false
        type: string

runs:
    using: 'composite'
    steps:
        - name: Use desired version of NodeJS from input
          if: ${{ inputs.node-version != '' }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}
              cache: npm

        - name: Use desired version of NodeJS from .nvmrc
          if: ${{ inputs.node-version == '' }}
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'
              cache: npm

        - name: Get node and npm version
          id: node-npm-version
          run: |
              echo "NODE_VERSION=$(node -v)" >> $GITHUB_OUTPUT
              echo "NPM_VERSION=$(npm -v)" >> $GITHUB_OUTPUT
          shell: bash

        - name: Cache node_modules
          id: cache-node_modules
          uses: actions/cache@v3
          with:
              path: '**/node_modules'
              key: node_modules-${{ runner.os }}-${{ steps.node-npm-version.outputs.NODE_VERSION }}/${{ steps.node-npm-version.outputs.NPM_VERSION }}-${{ hashFiles('package-lock.json') }}

        - name: Npm install
          if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
          run: npm ci
          shell: bash

        - name: Post-install
          if: ${{ steps.cache-node_modules.outputs.cache-hit == 'true' }}
          run: |
              npm run postinstall
              npx lerna run postinstall
          shell: bash
