name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js and install npm dependencies while managing all aspects of caching.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, the version specified in .nvmrc will be used.'
        required: false
        type: string

runs:
    using: 'composite'
    steps:
        - name: Use desired version of Node.js
          uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              check-latest: true
              cache: npm

        - name: Get Node.js and npm version
          id: node-version
          run: |
              echo "NODE_VERSION=$(node -v)" >> $GITHUB_OUTPUT
          shell: bash

        - name: Cache node_modules
          id: cache-node_modules
          uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
          with:
              path: '**/node_modules'
              key: node_modules-${{ runner.os }}-${{ steps.node-version.outputs.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

        - name: Install npm dependencies
          if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
          run: npm ci
          shell: bash

        # On cache hit, we run the post-install script to match the native `npm ci` behavior.
        # An example of this is to patch `node_modules` using patch-package.
        - name: Post-install
          if: ${{ steps.cache-node_modules.outputs.cache-hit == 'true' }}
          run: |
              # Run the post-install script for the root project.
              npm run postinstall
              # Run the post-install scripts for workspaces.
              npx lerna run postinstall
          shell: bash
