name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js and install npm dependencies while managing all aspects of caching.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, the version specified in .nvmrc will be used.'
        required: false
        type: string

runs:
    using: 'composite'
    steps:
        # Configure the desired version of node with caching.
        # Note: the node_modules directory is intentionally not cached.
        - name: Use desired version of Node.js
          uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
          with:
              node-version-file: ${{ inputs.node-version == '' && '.nvmrc' || '' }}
              node-version: ${{ inputs.node-version }}
              check-latest: true
              # Caching for npm dependencies is automatically enabled when package.json contains devEngines.packageManager field set to npm
              # cache: npm
              cache-dependency-path: |
                  package-lock.json
                  patches/**

        - name: Install npm dependencies
          run: |
              npm ci
          shell: bash

        - name: Upload npm logs as an artifact on failure
          uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
          if: failure()
          with:
              name: npm-logs
              path: C:\npm\cache\_logs
