
const socialList = {
	fivehundredpx: '500px',
	amazon: 'Amazon',
	apple: 'Apple',
	bandcamp: 'Bandcamp',
	behance: 'Behance',
	chain: 'Link',
	codepen: 'CodePen',
	deviantart: 'DeviantArt',
	digg: 'Digg',
	dribbble: 'Dribbble',
	dropbox: 'Dropbox',
	etsy: 'Etsy',
	facebook: 'Facebook',
	feed: 'RSS Feed',
	flickr: 'Flickr',
	foursquare: 'Foursquare',
	goodreads: 'Goodreads',
	google: 'Google',
	github: 'Github',
	instagram: 'Instagram',
	lastfm: 'Last.fm',
	linkedin: 'Linkedin',
	mail: 'E-mail',
	mastodon: 'Mastodon',
	meetup: 'Meetup',
	medium: 'Medium',
	pinterest: 'Pinterest',
	pocket: 'Pocket',
	reddit: 'Reddit',
	skype: 'Skype',
	slideshare: 'Slideshare',
	snapchat: 'Snapshot',
	soundcloud: 'Soundcloud',
	spotify: 'Spotify',
	stumbleupon: 'Stumbleupon',
	tumblr: 'Tumblr',
	twitch: 'Twitch',
	twitter: 'Twitter',
	vimeo: 'Vimeo',
	vk: 'VK',
	wordpress: 'WordPress',
	yelp: 'Yelp',
	youtube: 'YouTube',
};

export default socialList;
