/**
 * Internal dependencies
 */
import {
	AmazonIcon,
	BandcampIcon,
	BehanceIcon,
	BlueskyIcon,
	ChainIcon,
	CodepenIcon,
	DeviantArtIcon,
	DribbbleIcon,
	DropboxIcon,
	EtsyIcon,
	FacebookIcon,
	FeedIcon,
	FivehundredpxIcon,
	FlickrIcon,
	FoursquareIcon,
	GoodreadsIcon,
	GoogleIcon,
	GitHubIcon,
	GravatarIcon,
	InstagramIcon,
	LastfmIcon,
	LinkedInIcon,
	MailIcon,
	MastodonIcon,
	MeetupIcon,
	MediumIcon,
	PatreonIcon,
	PinterestIcon,
	PocketIcon,
	RedditIcon,
	SkypeIcon,
	SnapchatIcon,
	SoundCloudIcon,
	SpotifyIcon,
	TelegramIcon,
	ThreadsIcon,
	TiktokIcon,
	TumblrIcon,
	TwitchIcon,
	TwitterIcon,
	VimeoIcon,
	VkIcon,
	WhatsAppIcon,
	WordPressIcon,
	XIcon,
	YelpIcon,
	YouTubeIcon,
} from './icons';

const variations = [
	{
		isDefault: true,
		name: 'wordpress',
		attributes: { service: 'wordpress' },
		title: 'WordPress',
		icon: WordPressIcon,
		patterns: [ /^https:\/\/(.+\.)?wordpress\.(org|com)\/?(.+)?$/i ],
	},

	{
		name: 'fivehundredpx',
		attributes: { service: 'fivehundredpx' },
		title: '500px',
		icon: FivehundredpxIcon,
		patterns: [ /^https:\/\/500px\.com(\/.+)?$/i ],
	},
	{
		name: 'amazon',
		attributes: { service: 'amazon' },
		title: 'Amazon',
		icon: AmazonIcon,
		patterns: [ /^https:\/\/(.+\.)?amazon\.(\w+)(\/.+)?$/i ],
	},
	{
		name: 'bandcamp',
		attributes: { service: 'bandcamp' },
		title: 'Bandcamp',
		icon: BandcampIcon,
		patterns: [ /^https:\/\/(.+\.)bandcamp\.com\/?(.+)?$/i ],
	},
	{
		name: 'behance',
		attributes: { service: 'behance' },
		title: 'Behance',
		icon: BehanceIcon,
		patterns: [ /^https:\/\/(www\.)?behance\.net(\/.+)?$/i ],
	},
	{
		name: 'bluesky',
		attributes: { service: 'bluesky' },
		title: 'Bluesky',
		icon: BlueskyIcon,
	},
	{
		name: 'chain',
		attributes: { service: 'chain' },
		title: 'Link',
		icon: ChainIcon,
	},
	{
		name: 'codepen',
		attributes: { service: 'codepen' },
		title: 'CodePen',
		icon: CodepenIcon,
		patterns: [ /^https:\/\/codepen\.io(\/.+)?$/i ],
	},
	{
		name: 'deviantart',
		attributes: { service: 'deviantart' },
		title: 'DeviantArt',
		icon: DeviantArtIcon,
		patterns: [ /^https:\/\/(.+)\.deviantart\.com\/?(.+)?/i ],
	},
	{
		name: 'dribbble',
		attributes: { service: 'dribbble' },
		title: 'Dribbble',
		icon: DribbbleIcon,
		patterns: [ /^https:\/\/dribbble\.com(\/.+)?$/i ],
	},
	{
		name: 'dropbox',
		attributes: { service: 'dropbox' },
		title: 'Dropbox',
		icon: DropboxIcon,
		patterns: [ /^https:\/\/(www\.)?dropbox\.com(\/.+)?$/i ],
	},
	{
		name: 'etsy',
		attributes: { service: 'etsy' },
		title: 'Etsy',
		icon: EtsyIcon,
		patterns: [ /^https:\/\/(www\.)?etsy\.com(\/.+)?$/i ],
	},
	{
		name: 'facebook',
		attributes: { service: 'facebook' },
		title: 'Facebook',
		icon: FacebookIcon,
		patterns: [ /^https:\/\/(www\.)?facebook\.com(\/.+)?$/i ],
	},
	{
		name: 'feed',
		attributes: { service: 'feed' },
		title: 'RSS Feed',
		icon: FeedIcon,
		patterns: [ /(\/feed\/|\.rss|\.xml)$/i ],
	},
	{
		name: 'flickr',
		attributes: { service: 'flickr' },
		title: 'Flickr',
		icon: FlickrIcon,
		patterns: [ /^https:\/\/(www\.)?flickr\.com(\/.+)?$/i ],
	},
	{
		name: 'foursquare',
		attributes: { service: 'foursquare' },
		title: 'Foursquare',
		icon: FoursquareIcon,
		patterns: [ /^https:\/\/foursquare\.com(\/.+)?$/i ],
	},
	{
		name: 'goodreads',
		attributes: { service: 'goodreads' },
		title: 'Goodreads',
		icon: GoodreadsIcon,
		patterns: [ /^https:\/\/(www\.)?goodreads\.com(\/.+)?$/i ],
	},
	{
		name: 'google',
		attributes: { service: 'google' },
		title: 'Google',
		icon: GoogleIcon,
		patterns: [ /^https:\/\/(.+)\.google\.com(\/.+)?$/i ],
	},
	{
		name: 'github',
		attributes: { service: 'github' },
		title: 'GitHub',
		icon: GitHubIcon,
		patterns: [ /^https:\/\/github\.com(\/.+)?$/i ],
	},
	{
		name: 'gravatar',
		attributes: { service: 'gravatar' },
		title: 'Gravatar',
		icon: GravatarIcon,
		patterns: [ /^https:\/\/(www\.)?gravatar\.com(\/.+)?$/i ],
	},
	{
		name: 'instagram',
		attributes: { service: 'instagram' },
		title: 'Instagram',
		icon: InstagramIcon,
		patterns: [ /^https?:\/\/(www\.)?instagram\.com(\/.+)?$/i ],
	},
	{
		name: 'lastfm',
		attributes: { service: 'lastfm' },
		title: 'Last.fm',
		icon: LastfmIcon,
		patterns: [ /^https:\/\/(www\.)?last\.fm(\/.+)?$/i ],
	},
	{
		name: 'linkedin',
		attributes: { service: 'linkedin' },
		title: 'LinkedIn',
		icon: LinkedInIcon,
		patterns: [ /^https:\/\/(www\.)?linkedin\.com(\/.+)?$/i ],
	},
	{
		name: 'mail',
		attributes: { service: 'mail' },
		title: 'Mail',
		keywords: [ 'email', 'e-mail' ],
		icon: MailIcon,
	},
	{
		name: 'mastodon',
		attributes: { service: 'mastodon' },
		title: 'Mastodon',
		icon: MastodonIcon,
	},
	{
		name: 'meetup',
		attributes: { service: 'meetup' },
		title: 'Meetup',
		icon: MeetupIcon,
		patterns: [ /^https:\/\/(www\.)?meetup\.com(\/.+)?$/i ],
	},
	{
		name: 'medium',
		attributes: { service: 'medium' },
		title: 'Medium',
		icon: MediumIcon,
		patterns: [ /^https:\/\/medium\.com(\/.+)?$/i ],
	},
	{
		name: 'patreon',
		attributes: { service: 'patreon' },
		title: 'Patreon',
		icon: PatreonIcon,
		patterns: [ /^https:\/\/(www\.)?patreon\.com(\/.+)?$/i ],
	},
	{
		name: 'pinterest',
		attributes: { service: 'pinterest' },
		title: 'Pinterest',
		icon: PinterestIcon,
		patterns: [ /^https:\/\/(www\.)?pinterest\.com(\/.+)?$/i ],
	},
	{
		name: 'pocket',
		attributes: { service: 'pocket' },
		title: 'Pocket',
		icon: PocketIcon,
		patterns: [ /^https:\/\/getpocket\.com(\/.+)?$/i ],
	},
	{
		name: 'reddit',
		attributes: { service: 'reddit' },
		title: 'Reddit',
		icon: RedditIcon,
		patterns: [ /^https:\/\/(www\.)?reddit\.com(\/.+)?$/i ],
	},
	{
		name: 'skype',
		attributes: { service: 'skype' },
		title: 'Skype',
		icon: SkypeIcon,
		patterns: [ /^https:\/\/join\.skype\.com(\/.+)?$/i ],
	},
	{
		name: 'snapchat',
		attributes: { service: 'snapchat' },
		title: 'Snapchat',
		icon: SnapchatIcon,
		patterns: [ /^https:\/\/(www\.)?snapchat\.com(\/.+)?$/i ],
	},
	{
		name: 'soundcloud',
		attributes: { service: 'soundcloud' },
		title: 'SoundCloud',
		icon: SoundCloudIcon,
		patterns: [ /^https:\/\/soundcloud\.com(\/.+)?$/i ],
	},
	{
		name: 'spotify',
		attributes: { service: 'spotify' },
		title: 'Spotify',
		icon: SpotifyIcon,
		patterns: [ /^https:\/\/open\.spotify\.com(\/.+)?$/i ],
	},
	{
		name: 'telegram',
		attributes: { service: 'telegram' },
		title: 'Telegram',
		icon: TelegramIcon,
		patterns: [ /^https:\/\/t\.me(\/.+)?$/i ],
	},
	{
		name: 'threads',
		attributes: { service: 'threads' },
		title: 'Threads',
		icon: ThreadsIcon,
		patterns: [ /^https:\/\/(www\.)?threads\.net(\/.+)?$/i ],
	},
	{
		name: 'tiktok',
		attributes: { service: 'tiktok' },
		title: 'TikTok',
		icon: TiktokIcon,
		patterns: [ /^https:\/\/(www\.)?tiktok\.com(\/.+)?$/i ],
	},
	{
		name: 'tumblr',
		attributes: { service: 'tumblr' },
		title: 'Tumblr',
		icon: TumblrIcon,
		patterns: [ /^https:\/\/(.+)\.tumblr\.com\/?(.+)?/i ],
	},
	{
		name: 'twitch',
		attributes: { service: 'twitch' },
		title: 'Twitch',
		icon: TwitchIcon,
		patterns: [ /^https:\/\/(www\.)?twitch\.tv(\/.+)?$/i ],
	},
	{
		name: 'twitter',
		attributes: { service: 'twitter' },
		title: 'Twitter',
		icon: TwitterIcon,
	},
	{
		name: 'vimeo',
		attributes: { service: 'vimeo' },
		title: 'Vimeo',
		icon: VimeoIcon,
		patterns: [ /^https:\/\/vimeo\.com(\/.+)?$/i ],
	},
	{
		name: 'vk',
		attributes: { service: 'vk' },
		title: 'VK',
		icon: VkIcon,
		patterns: [ /^https:\/\/vk\.com(\/.+)?$/i ],
	},
	{
		name: 'whatsapp',
		attributes: { service: 'whatsapp' },
		title: 'WhatsApp',
		icon: WhatsAppIcon,
	},
	{
		name: 'x',
		attributes: { service: 'x' },
		keywords: [ 'twitter' ],
		title: 'X',
		icon: XIcon,
		patterns: [
			/^https:\/\/x\.com(\/.+)?$/i,
			/^https:\/\/twitter\.com(\/.+)?$/i,
		],
	},
	{
		name: 'yelp',
		attributes: { service: 'yelp' },
		title: 'Yelp',
		icon: YelpIcon,
		patterns: [ /^https:\/\/(www\.)?yelp\.com(\/.+)?$/i ],
	},
	{
		name: 'youtube',
		attributes: { service: 'youtube' },
		title: 'YouTube',
		icon: YouTubeIcon,
		patterns: [ /^https:\/\/(www\.)?youtube\.com(\/.+)?$/i ],
	},
];

/**
 * Add `isActive` function to all `social link` variations, if not defined.
 * `isActive` function is used to find a variation match from a created
 *  Block by providing its attributes.
 */
variations.forEach( ( variation ) => {
	if ( variation.isActive ) {
		return;
	}
	variation.isActive = ( blockAttributes, variationAttributes ) =>
		blockAttributes.service === variationAttributes.service;
} );

export default variations;
