/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "handle": string;
  readonly "handle-corner": string;
  readonly "handle-horizontal": string;
  readonly "resizing": string;
};
export = styles;

