/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "drag-preview": string;
  readonly "grid": string;
  readonly "tile": string;
  readonly "tile-edit-mode": string;
};
export = styles;

