/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "actions": string;
  readonly "description": string;
  readonly "icon": string;
  readonly "root": string;
  readonly "title": string;
  readonly "visual": string;
};
export = styles;

