/**
 * Inserts new contents within the token boundaries.
 *
 * @param {Object} targetAst The remark AST of the file where the new contents are to be embedded.
 * @param {Object} newContents The new contents to be embedded in remark AST format.
 * @return {boolean} Whether the contents were embedded or not.
 */
const embed = function( targetAst, newContents ) {
	const startIndex = targetAst.children.findIndex(
		( node ) => node.type === 'html' && node.value === '<!-- Autogenerated API docs start -->'
	);
	const endIndex = targetAst.children.findIndex(
		( node ) => node.type === 'html' && node.value === '<!-- Autogenerated API docs end -->'
	);
	if ( startIndex !== -1 && endIndex !== -1 && startIndex < endIndex ) {
		targetAst.children.splice( startIndex + 1, endIndex - startIndex - 1, newContents );
		return true;
	}
	return false;
};

module.exports = embed;
