/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "date": string;
  readonly "root": string;
  readonly "thumbImage": string;
  readonly "thumbPlaceholder": string;
  readonly "titleHeader": string;
  readonly "titleLink": string;
  readonly "titleRow": string;
};
export = styles;

