/**
 * Install managed workspace settings without replacing contributor customizations.
 * Runs with Node's type stripping on Windows, macOS, and Linux.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getEditorSettings, type Editor } from './editor-settings.mts';

const REPO_ROOT = fileURLToPath( new URL( '../../../', import.meta.url ) );
const editors: Editor[] = [ 'vscode', 'zed' ];
const requestedEditors = process.argv.slice( 2 );

if (
	requestedEditors.some(
		( editor ) => ! editors.includes( editor as Editor )
	)
) {
	console.error( 'Supported editors: vscode, zed.' );
	process.exit( 1 );
}

for ( const editor of requestedEditors.length
	? ( requestedEditors as Editor[] )
	: editors ) {
	const name = editor === 'vscode' ? 'VS Code' : 'Zed';
	const managedComment = `// This is a managed ${ name } settings file.`;
	const destFile = path.join( REPO_ROOT, `.${ editor }`, 'settings.json' );
	const settings = `${ managedComment }\n// Generated by tools/monorepo/scripts/editor-settings.mts.\n// To customize these settings and keep your changes, delete the first line.\n${ JSON.stringify( getEditorSettings( editor, REPO_ROOT ), null, '\t' ) }\n`;

	try {
		if ( existsSync( destFile ) ) {
			const current = readFileSync( destFile, 'utf8' );
			if ( current === settings ) {
				console.log( `${ name }: managed settings are up to date.` );
				continue;
			}
			if ( current.split( /\r?\n/, 1 )[ 0 ] !== managedComment ) {
				console.log(
					`${ name }: custom settings file; leaving it unchanged.`
				);
				continue;
			}
		}
		mkdirSync( path.dirname( destFile ), { recursive: true } );
		writeFileSync( destFile, settings );
		console.log( `${ name }: installed managed settings.` );
	} catch ( error ) {
		console.error(
			`${ name }: could not install workspace settings.`,
			error
		);
		process.exitCode = 2;
	}
}
