/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "arrow": string;
  readonly "arrow-fill": string;
  readonly "arrow-stroke": string;
  readonly "backdrop": string;
  readonly "popup": string;
  readonly "positioner": string;
  readonly "surface": string;
  readonly "title": string;
};
export = styles;

