/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "indeterminate-slide": string;
  readonly "indicator": string;
  readonly "is-indeterminate": string;
  readonly "progress-element": string;
  readonly "track": string;
};
export = styles;

