/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-dragging": string;
  readonly "is-resizing": string;
  readonly "item": string;
  readonly "item-content": string;
  readonly "preview-overlay": string;
  readonly "wp-grid-item-placeholder-in": string;
};
export = styles;

