/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "label-text": string;
  readonly "root": string;
  readonly "tooltip": string;
  readonly "tooltip-wrapper": string;
};
export = styles;

