/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "circle-indicator": string;
  readonly "circle-indicator-wrapper": string;
  readonly "circle-root": string;
};
export = styles;

