/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "input-layout": string;
  readonly "input-layout-slot": string;
  readonly "is-borderless": string;
  readonly "is-disabled": string;
  readonly "is-padding-minimal": string;
  readonly "is-size-compact": string;
  readonly "is-size-small": string;
  readonly "slot-wrapper": string;
};
export = styles;

