/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "error": string;
  readonly "percentage": string;
  readonly "root": string;
  readonly "success": string;
  readonly "warning": string;
};
export = styles;

