/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "body-lg": string;
  readonly "body-md": string;
  readonly "body-sm": string;
  readonly "body-xl": string;
  readonly "heading-2xl": string;
  readonly "heading-lg": string;
  readonly "heading-md": string;
  readonly "heading-sm": string;
  readonly "heading-xl": string;
  readonly "text": string;
};
export = styles;

