
const socialList = {
	share: [],
	fivehundredpx: [ '500px.com' ],
	amazon: [
		'amazon.com',
		'amazon.cn',
		'amazon.in',
		'amazon.fr',
		'amazon.de',
		'amazon.it',
		'amazon.nl',
		'amazon.es',
		'amazon.co',
		'amazon.ca',
	],
	apple: [
		'apple.com',
		'itunes.com',
	],
	bandcamp: [ 'bandcamp.com' ],
	behance: [ 'behance.net' ],
	chain: [],
	codepen: [ 'codepen.io' ],
	deviantart: [ 'deviantart.com' ],
	digg: [ 'digg.com' ],
	dribbble: [ 'dribbble.com' ],
	dropbox: [ 'dropbox.com' ],
	etsy: [ 'etsy.com' ],
	facebook: [
		'facebook.com',
		'fb.me',
	],
	feed: [ 'feed', 'rss.xml', 'atom.xml' ],
	flickr: [ 'flickr.com' ],
	foursquare: [ 'foursquare.com' ],
	goodreads: [ 'goodreads.com' ],
	google: [ 'google.com' ],
	github: [ 'github.com', 'github.io' ],
	instagram: [ 'instagram.com' ],
	lastfm: [ 'last.fm' ],
	linkedin: [ 'linkedin.com' ],
	mail: [ 'mailto:' ],
	meetup: [ 'meetup.com' ],
	medium: [ 'medium.com' ],
	pinterest: [ 'pinterest.com' ],
	pocket: [ 'getpocket.com' ],
	reddit: [ 'reddit.com' ],
	skype: [ 'skype.com' ],
	slideshare: [ 'slideshare.net' ],
	snapchat: [ 'snapshot.com' ],
	soundcloud: [ 'soundcloud.com' ],
	spotify: [ 'spotify.com' ],
	stumbleupon: [ 'stumbleupon.com' ],
	tumblr: [ 'tumblr.com' ],
	twitch: [ 'twitch.tv' ],
	twitter: [ 'twitter.com' ],
	vimeo: [ 'vimeo.com' ],
	vk: [ 'vk.com' ],
	wordpress: [ 'wordpress.org', 'wordpress.com' ],
	yelp: [ 'yelp.com' ],
	youtube: [ 'youtube.com' ],
};

export default socialList;
