name: 'Report flaky tests'
description: 'Report flaky tests as a comment on the pull request'
inputs:
    repo-token:
        description: 'GitHub token'
        required: true
    artifact-path:
        description: 'The path of the downloaded artifact'
        required: true
        default: 'flaky-tests'
runs:
    using: 'node24'
    main: 'build/index.cjs'
