/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "content-wrapper": string;
  readonly "padding-medium": string;
  readonly "padding-small": string;
};
export = styles;

