/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "glint": string;
  readonly "root": string;
  readonly "welcomeVersionGlint": string;
};
export = styles;

