/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "backdrop": string;
  readonly "content": string;
  readonly "footer": string;
  readonly "header": string;
  readonly "is-auto": string;
  readonly "is-large": string;
  readonly "is-medium": string;
  readonly "is-small": string;
  readonly "is-stretch": string;
  readonly "popup": string;
  readonly "title": string;
  readonly "viewport": string;
};
export = styles;

