/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "drag-preview-frame": string;
  readonly "drag-preview-frame__lift": string;
  readonly "dragPreviewFrameExiting": string;
  readonly "lanes": string;
  readonly "wp-grid-drag-preview-scale-enter": string;
  readonly "wp-grid-drag-preview-scale-exit": string;
  readonly "wp-grid-drag-preview-shadow-enter": string;
  readonly "wp-grid-drag-preview-shadow-exit": string;
};
export = styles;

