/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "back-button": string;
  readonly "content": string;
  readonly "footer": string;
  readonly "scrollable": string;
};
export = styles;

