export interface FixtureItem {
	id: string;
	value: string;
}

export const ITEMS: FixtureItem[] = [
	{ id: 'apple', value: 'Apple' },
	{ id: 'apricot', value: 'Apricot' },
	{ id: 'banana', value: 'Banana' },
	{ id: 'blackberry', value: 'Blackberry' },
	{ id: 'blueberry', value: 'Blueberry' },
	{ id: 'boysenberry', value: 'Boysenberry' },
	{ id: 'breadfruit', value: 'Breadfruit' },
	{ id: 'cantaloupe', value: 'Cantaloupe' },
	{ id: 'cherry', value: 'Cherry' },
	{ id: 'clementine', value: 'Clementine' },
	{ id: 'coconut', value: 'Coconut' },
	{ id: 'cranberry', value: 'Cranberry' },
	{ id: 'dragonfruit', value: 'Dragonfruit' },
	{ id: 'durian', value: 'Durian' },
	{ id: 'elderberry', value: 'Elderberry' },
	{ id: 'fig', value: 'Fig' },
	{ id: 'gooseberry', value: 'Gooseberry' },
	{ id: 'grape', value: 'Grape' },
	{ id: 'grapefruit', value: 'Grapefruit' },
	{ id: 'guava', value: 'Guava' },
	{ id: 'honeydew', value: 'Honeydew' },
	{ id: 'jackfruit', value: 'Jackfruit' },
	{ id: 'kiwi', value: 'Kiwi' },
	{ id: 'kumquat', value: 'Kumquat' },
	{ id: 'lemon', value: 'Lemon' },
	{ id: 'lime', value: 'Lime' },
	{ id: 'longan', value: 'Longan' },
	{ id: 'lychee', value: 'Lychee' },
	{ id: 'mandarin', value: 'Mandarin' },
	{ id: 'mango', value: 'Mango' },
	{ id: 'mangosteen', value: 'Mangosteen' },
	{ id: 'mulberry', value: 'Mulberry' },
	{ id: 'nectarine', value: 'Nectarine' },
	{ id: 'orange', value: 'Orange' },
	{ id: 'papaya', value: 'Papaya' },
	{ id: 'passionfruit', value: 'Passionfruit' },
	{ id: 'peach', value: 'Peach' },
	{ id: 'pear', value: 'Pear' },
	{ id: 'persimmon', value: 'Persimmon' },
	{ id: 'pineapple', value: 'Pineapple' },
	{ id: 'plum', value: 'Plum' },
	{ id: 'pomegranate', value: 'Pomegranate' },
	{ id: 'quince', value: 'Quince' },
	{ id: 'rambutan', value: 'Rambutan' },
	{ id: 'raspberry', value: 'Raspberry' },
	{ id: 'soursop', value: 'Soursop' },
	{ id: 'starfruit', value: 'Starfruit' },
	{ id: 'strawberry', value: 'Strawberry' },
	{ id: 'tangerine', value: 'Tangerine' },
	{ id: 'watermelon', value: 'Watermelon' },
];
