export interface FixtureItem {
	value: string;
	label: string;
}

export const ITEMS: FixtureItem[] = [
	{ value: 'apple', label: 'Apple' },
	{ value: 'apricot', label: 'Apricot' },
	{ value: 'banana', label: 'Banana' },
	{ value: 'blackberry', label: 'Blackberry' },
	{ value: 'blueberry', label: 'Blueberry' },
	{ value: 'boysenberry', label: 'Boysenberry' },
	{ value: 'breadfruit', label: 'Breadfruit' },
	{ value: 'cantaloupe', label: 'Cantaloupe' },
	{ value: 'cherry', label: 'Cherry' },
	{ value: 'clementine', label: 'Clementine' },
	{ value: 'coconut', label: 'Coconut' },
	{ value: 'cranberry', label: 'Cranberry' },
	{ value: 'dragonfruit', label: 'Dragonfruit' },
	{ value: 'durian', label: 'Durian' },
	{ value: 'elderberry', label: 'Elderberry' },
	{ value: 'fig', label: 'Fig' },
	{ value: 'gooseberry', label: 'Gooseberry' },
	{ value: 'grape', label: 'Grape' },
	{ value: 'grapefruit', label: 'Grapefruit' },
	{ value: 'guava', label: 'Guava' },
	{ value: 'honeydew', label: 'Honeydew' },
	{ value: 'jackfruit', label: 'Jackfruit' },
	{ value: 'kiwi', label: 'Kiwi' },
	{ value: 'kumquat', label: 'Kumquat' },
	{ value: 'lemon', label: 'Lemon' },
	{ value: 'lime', label: 'Lime' },
	{ value: 'longan', label: 'Longan' },
	{ value: 'lychee', label: 'Lychee' },
	{ value: 'mandarin', label: 'Mandarin' },
	{ value: 'mango', label: 'Mango' },
	{ value: 'mangosteen', label: 'Mangosteen' },
	{ value: 'mulberry', label: 'Mulberry' },
	{ value: 'nectarine', label: 'Nectarine' },
	{ value: 'orange', label: 'Orange' },
	{ value: 'papaya', label: 'Papaya' },
	{ value: 'passionfruit', label: 'Passionfruit' },
	{ value: 'peach', label: 'Peach' },
	{ value: 'pear', label: 'Pear' },
	{ value: 'persimmon', label: 'Persimmon' },
	{ value: 'pineapple', label: 'Pineapple' },
	{ value: 'plum', label: 'Plum' },
	{ value: 'pomegranate', label: 'Pomegranate' },
	{ value: 'quince', label: 'Quince' },
	{ value: 'rambutan', label: 'Rambutan' },
	{ value: 'raspberry', label: 'Raspberry' },
	{ value: 'soursop', label: 'Soursop' },
	{ value: 'starfruit', label: 'Starfruit' },
	{ value: 'strawberry', label: 'Strawberry' },
	{ value: 'tangerine', label: 'Tangerine' },
	{ value: 'watermelon', label: 'Watermelon' },
];
