<?php
function block_core_my_block() {
}

function block_core_my_block_with_some_postfix() {
}

function block_core_my_blockwith_no_underscore_after_the_prefix() {
}

function render_block_core_my_block() {
}

function render_block_core_my_block_with_some_postfix() {
}

function render_block_core_my_blockwith_no_underscore_after_the_prefix() {
}

function register_block_core_my_block() {
}

function register_block_core_my_block_with_some_postfix() {
}

function register_block_core_my_blockwith_no_underscore_after_the_prefix() {
}

class MyClass {
	// Represents a non-prefixed method within the class.
	public function some_non_prefixed_class_method() {
	}
}

function foo() {
}
