/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "border-bottom": string;
  readonly "border-left": string;
  readonly "border-right": string;
  readonly "border-top": string;
  readonly "dotted": string;
  readonly "grid": string;
  readonly "secondary": string;
  readonly "surface": string;
};
export = styles;

