/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "field": string;
  readonly "help": string;
  readonly "label": string;
  readonly "wrapper": string;
};
export = styles;

