/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "button": string;
  readonly "icon": string;
  readonly "is-brand": string;
  readonly "is-compact": string;
  readonly "is-loading": string;
  readonly "is-minimal": string;
  readonly "is-neutral": string;
  readonly "is-outline": string;
  readonly "is-small": string;
  readonly "is-solid": string;
  readonly "is-unstyled": string;
  readonly "loading-animation": string;
};
export = styles;

