/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "canvas": string;
  readonly "card": string;
  readonly "viewport": string;
};
export = styles;

