/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "item": string;
  readonly "li": string;
  readonly "list": string;
};
export = styles;

