/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-line-clamp": string;
  readonly "is-single-line": string;
  readonly "truncate": string;
};
export = styles;

