<?php

require __DIR__ .'/../lib/class-walker-blocks.php';

/**
 * Test Elements Hook.
 *
 * @package Gutenberg
 */
class Walker_Blocks_Test extends WP_UnitTestCase {

	/**
	 * @var array[]
	 */
	private $blocks = [];

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->blocks_html = '
<!-- wp:navigation -->
<!-- wp:navigation-link {"label":"No To BYOM: Bring Your Own Motivation","type":"post","id":89,"url":"https://adamadam.blog/2021/10/14/no-to-byom-bring-your-own-motivation/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"No To BYOM: Bring Your Own Motivation","type":"post","id":89,"url":"https://adamadam.blog/2021/10/14/no-to-byom-bring-your-own-motivation/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-link {"label":"No To BYOM: Bring Your Own Motivation","type":"post","id":89,"url":"https://adamadam.blog/2021/10/14/no-to-byom-bring-your-own-motivation/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-submenu {"label":"Don’t Waste Time On Boring Programming Lessons","type":"post","id":77,"url":"https://adamadam.blog/2021/10/03/dont-waste-time-on-boring-programming-lessons/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"No To BYOM: Bring Your Own Motivation","type":"post","id":89,"url":"https://adamadam.blog/2021/10/14/no-to-byom-bring-your-own-motivation/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->';
		// @TODO compare to the shape of WP menus

		$this->blocks = array_filter(
			parse_blocks( $this->blocks_html ),
			function( $block ) {
				return isset( $block['blockName'] );
			}
		);


		print_r($this->blocks);
	}

	/**
	 *
	 */
	public function test_render_block_idea() {
		add_filter( 'render_block', function($block_content, $block_data) {
			die($block_content);
			return $block_content;
		}, 10, 2);
		$this->assertSame(
			<<<'HTML'

<div class="wp-block-columns">
<div class="wp-block-column">
<p>test</p>
</div>



<div class="wp-block-column">
<p>test3</p>
</div>
</div>

HTML
			,
			do_blocks($this->blocks_html)
		);
	}
//
//	/**
//	 *
//	 */
//	public function test_rendering_the_entire_block_tree() {
//		$walker = new Walker_Nav_Menu_Block();
//
//		$output = $walker->walk( $this->blocks, 1 );
//		$this->assertSame(
//			<<<'HTML'
//
//<div class="wp-block-columns">
//<div class="wp-block-column">
//<p>test</p>
//</div>
//
//
//
//<div class="wp-block-column">
//<p>test3</p>
//</div>
//</div>
//
//HTML
//			,
//			$output
//		);
//	}
//
//	/**
//	 *
//	 */
//	public function test_rendering_the_top_level_blocks() {
//		$walker = new Walker_Blocks();
//
//		$output = $walker->walk( $this->blocks, 0 );
//		$this->assertSame(
//			<<<'HTML'
//
//<div class="wp-block-columns">
//</div>
//
//HTML
//			,
//			$output
//		);
//	}

}
