/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "icon": string;
  readonly "input-wrapper": string;
  readonly "linked-button-wrapper": string;
  readonly "range-control": string;
  readonly "reset-button": string;
  readonly "unit-control": string;
};
export = styles;

