/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "block": string;
  readonly "expanded-column": string;
  readonly "expanded-row": string;
  readonly "flex": string;
  readonly "item": string;
  readonly "items-column": string;
  readonly "items-row": string;
};
export = styles;

