/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "indicator": string;
  readonly "spinner": string;
  readonly "spinner-spin": string;
  readonly "track": string;
};
export = styles;

