/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "centered-border-control": string;
  readonly "linked-border-control": string;
  readonly "linked-button": string;
  readonly "right-border-control": string;
  readonly "split-controls": string;
  readonly "visualizer": string;
  readonly "wrapper": string;
};
export = styles;

