/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "emptyState": string;
  readonly "eventIcon": string;
  readonly "eventNone": string;
  readonly "listArea": string;
  readonly "meta": string;
  readonly "root": string;
  readonly "titleLink": string;
};
export = styles;

