/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "backRow": string;
  readonly "body": string;
  readonly "fill": string;
  readonly "formContainer": string;
  readonly "listPane": string;
  readonly "primaryPane": string;
  readonly "row": string;
};
export = styles;

