<?php
/**
 * It's time block pattern.
 *
 * @package gutenberg
 */

return array(
	'title'      => __( 'It\'s time', 'gutenberg' ),
	'categories' => array( 'text', 'columns' ),
	'content'    => "<!-- wp:group {\"align\":\"wide\",\"style\":{\"color\":{\"background\":\"#ffffff\"}}} -->\n<div class=\"wp-block-group alignwide has-background\" style=\"background-color:#ffffff\"><div class=\"wp-block-group__inner-container\"><!-- wp:columns {\"align\":\"full\"} -->\n<div class=\"wp-block-columns alignfull\"><!-- wp:column -->\n<div class=\"wp-block-column\"><!-- wp:paragraph {\"style\":{\"color\":{\"text\":\"#df3100\"}}} -->\n<p class=\"has-text-color\" style=\"color:#df3100\"><strong>NEW</strong></p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph {\"style\":{\"color\":{\"text\":\"#000000\"}}} -->\n<p class=\"has-text-color\" style=\"color:#000000\">John Lenwood \"Jackie\" McLean was an American jazz alto saxophonist, composer, bandleader, and educator, and is one of the few musicians to be elected to the DownBeat Hall of Fame in the year of their death.</p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:column -->\n\n<!-- wp:column -->\n<div class=\"wp-block-column\"><!-- wp:paragraph {\"style\":{\"color\":{\"text\":\"#ffffff\"}}} -->\n<p class=\"has-text-color\" style=\"color:#ffffff\"> space</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph {\"style\":{\"color\":{\"text\":\"#000000\"}}} -->\n<p class=\"has-text-color\" style=\"color:#000000\">Derek Ansell's full-length biography of McLean, Sugar Free Saxophone (London: Northway Books, 2012), details the story of his career and provides a full analysis of his music on record.</p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:column --></div>\n<!-- /wp:columns -->\n\n<!-- wp:columns {\"align\":\"wide\"} -->\n<div class=\"wp-block-columns alignwide\"><!-- wp:column {\"width\":0} -->\n<div class=\"wp-block-column\" style=\"flex-basis:0%\"></div>\n<!-- /wp:column -->\n\n<!-- wp:column {\"width\":100} -->\n<div class=\"wp-block-column\" style=\"flex-basis:100%\"><!-- wp:paragraph {\"align\":\"center\",\"style\":{\"color\":{\"text\":\"#000000\"},\"typography\":{\"lineHeight\":\"1\",\"fontSize\":160}}} -->\n<p class=\"has-text-align-center has-text-color\" style=\"line-height:1;font-size:160px;color:#000000\"><strong><em>it's time</em></strong> </p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:column --></div>\n<!-- /wp:columns --></div></div>\n<!-- /wp:group -->",
);
