<?php
/**
 * Large header and two columns of text block pattern.
 *
 * @package gutenberg
 */

return array(
	'title'         => __( 'Large header & two columns of text', 'gutenberg' ),
	'categories'    => array( 'header' ),
  'content'       => "<!-- wp:group {\"align\":\"wide\"} -->\n<div class=\"wp-block-group alignwide\"><div class=\"wp-block-group__inner-container\"><!-- wp:cover {\"customGradient\":\"radial-gradient(rgb(238,238,238) 0%,rgb(169,184,195) 100%)\",\"contentPosition\":\"center center\",\"align\":\"wide\"} -->\n<div class=\"wp-block-cover alignwide has-background-dim has-background-gradient is-position-center-center\" style=\"background:radial-gradient(rgb(238,238,238) 0%,rgb(169,184,195) 100%)\"><div class=\"wp-block-cover__inner-container\"><!-- wp:paragraph {\"align\":\"center\",\"placeholder\":\"Write title…\",\"textColor\":\"black\",\"style\":{\"typography\":{\"fontSize\":90,\"lineHeight\":\"1.2\"}}} -->\n<p class=\"has-text-align-center has-black-color has-text-color\" style=\"line-height:1.2;font-size:90px\"><strong>Heading</strong></p>\n<!-- /wp:paragraph --></div></div>\n<!-- /wp:cover -->\n\n<!-- wp:columns {\"align\":\"wide\"} -->\n<div class=\"wp-block-columns alignwide\"><!-- wp:column -->\n<div class=\"wp-block-column\"><!-- wp:paragraph -->\n<p>This language, which they did not understand, and the extraordinary appearance of the knight, increased their laughter, which also increased his displeasure, and he would probably have shown it in a less civil way, but for the timely arrival of the innkeeper.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>He was a man whose burden of fat inclined him to peace and quietness, yet when he observed such a strange disguise of human shape in his old armour and equipage, he could hardly forbear laughter; but having the fear of such a warlike appearance before his eyes, he resolved to give him good words, and therefore accosted him civilly.</p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:column -->\n\n<!-- wp:column -->\n<div class=\"wp-block-column\"><!-- wp:paragraph -->\n<p>\"Sir Knight,\" said he, \"if your worship be disposed to alight, you will fail of nothing here but of a bed as for all other accommodations, you may be supplied to your mind.\"</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Don Quixote observing the humility of the governor of the castle, \"Signor Castellano,\" said he, \"the least thing in the world suffices me; for arms are the only things I value, and combat is my bed of repose.\" The host thought from Don Quixote calling him Castellano that he took him for an honest Castilian, while he was really an Andalusian of the coast of Saint Lucar, as great a thief as Cacus, and as full of fun and mischief as a schoolboy or a page.</p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:column --></div>\n<!-- /wp:columns --></div></div>\n<!-- /wp:group -->",
  'viewportWidth' => 1000,
);
