/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "unavailable": string;
  readonly "widget-chrome": string;
  readonly "widget-chrome-content": string;
  readonly "widget-chrome-header-icon": string;
};
export = styles;

