/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "content": string;
  readonly "fullbleed": string;
  readonly "header": string;
  readonly "root": string;
};
export = styles;

