#!/usr/bin/env node

/**
 * Generates sibling TypeScript declarations for CSS Modules using
 * typed-css-modules (tcm). SCSS modules are compiled with sass-embedded first
 * so class names match what the build extracts.
 *
 * Usage:
 *   node tools/css-modules/generate.mjs
 *   node tools/css-modules/generate.mjs --listDifferent
 */

import path from 'node:path';
import { readFile, unlink } from 'node:fs/promises';
import fg from 'fast-glob';
import { compile as compileSass, NodePackageImporter } from 'sass-embedded';
import tcm from 'typed-css-modules';

const DtsCreator = tcm.default ?? tcm;

const ROOT = path.resolve( import.meta.dirname, '../..' );
const LIST_DIFFERENT = process.argv.includes( '--listDifferent' );

const SOURCE_GLOBS = [ '**/*.module.css', '**/*.module.scss' ];
const DECLARATION_GLOBS = [ '**/*.module.css.d.ts', '**/*.module.scss.d.ts' ];
const IGNORE = [
	'**/node_modules/**',
	'**/build/**',
	'**/build-*/**',
	'**/vendor/**',
	'**/fixtures/**',
];

const HEADER =
	'/* This file is generated by `npm run css-modules:generate`. Do not edit. */\n\n';

const SASS_OPTIONS = {
	importers: [ new NodePackageImporter( ROOT ) ],
	loadPaths: [
		path.join( ROOT, 'node_modules' ),
		path.join( ROOT, 'packages/base-styles' ),
	],
};

/**
 * @param {string} formatted
 * @return {string} Declaration file contents.
 */
function postprocess( formatted ) {
	return HEADER + formatted;
}

/**
 * @param {string} filePath Absolute path to a CSS or SCSS module.
 * @return {Promise<string|undefined>} Precompiled CSS for SCSS modules.
 */
async function scssContents( filePath ) {
	if ( ! filePath.endsWith( '.scss' ) ) {
		return undefined;
	}
	return compileSass( filePath, SASS_OPTIONS ).css;
}

/**
 * @param {string} relativePath Path from the repo root using POSIX separators.
 */
function logRelative( relativePath ) {
	return relativePath.split( path.sep ).join( '/' );
}

const sourceFiles = (
	await fg( SOURCE_GLOBS, {
		cwd: ROOT,
		absolute: true,
		ignore: IGNORE,
	} )
).sort();

const expectedDeclarations = new Set(
	sourceFiles.map( ( filePath ) => `${ filePath }.d.ts` )
);

const existingDeclarations = (
	await fg( DECLARATION_GLOBS, {
		cwd: ROOT,
		absolute: true,
		ignore: IGNORE,
	} )
).sort();

const creator = new DtsCreator( {
	rootDir: ROOT,
	EOL: '\n',
} );

let hasErrors = false;
let written = 0;

for ( const filePath of sourceFiles ) {
	const relativePath = path.relative( ROOT, filePath );
	try {
		const contents = await scssContents( filePath );
		const dts = await creator.create( filePath, contents, true );
		if ( LIST_DIFFERENT ) {
			const ok = await dts.checkFile( postprocess );
			if ( ! ok ) {
				hasErrors = true;
			}
		} else {
			const outputPath = dts.outputFilePath;
			const previous = await readFile( outputPath, 'utf8' ).catch(
				() => null
			);
			await dts.writeFile( postprocess );
			const next = await readFile( outputPath, 'utf8' );
			if ( previous !== next ) {
				written += 1;
				console.log( `Wrote ${ logRelative( relativePath ) }.d.ts` );
			}
		}
	} catch ( error ) {
		hasErrors = true;
		const message =
			error instanceof Error ? error.message : String( error );
		console.error(
			`Failed to process ${ logRelative( relativePath ) }: ${ message }`
		);
	}
}

for ( const declarationPath of existingDeclarations ) {
	if ( expectedDeclarations.has( declarationPath ) ) {
		continue;
	}
	const relativePath = path.relative( ROOT, declarationPath );
	if ( LIST_DIFFERENT ) {
		hasErrors = true;
		console.error(
			`Orphan CSS module declaration (no matching stylesheet): ${ logRelative(
				relativePath
			) }`
		);
		continue;
	}
	await unlink( declarationPath );
	written += 1;
	console.log( `Removed ${ logRelative( relativePath ) }` );
}

if ( LIST_DIFFERENT ) {
	if ( hasErrors ) {
		console.error(
			'\nCSS module declarations are stale. Run `npm run css-modules:generate` and commit the result.'
		);
		process.exit( 1 );
	}
	console.log(
		`CSS module declarations are up to date (${ sourceFiles.length } files).`
	);
	process.exit( 0 );
}

if ( hasErrors ) {
	process.exit( 1 );
}

if ( written === 0 ) {
	console.log(
		`CSS module declarations already up to date (${ sourceFiles.length } files).`
	);
} else {
	console.log(
		`Updated ${ written } CSS module declaration${
			written === 1 ? '' : 's'
		}.`
	);
}
