/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "chips-edit-area": string;
  readonly "chips-list": string;
  readonly "input": string;
  readonly "input-layout": string;
};
export = styles;

