/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "help": string;
  readonly "icon": string;
  readonly "identity": string;
  readonly "link": string;
  readonly "overlay": string;
  readonly "popover-popup": string;
  readonly "title": string;
  readonly "toolbar": string;
  readonly "widget-header": string;
};
export = styles;

