/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "indicator": string;
  readonly "indicator-icon": string;
  readonly "indicator-jump": string;
  readonly "indicator-spinner": string;
  readonly "is-invalid": string;
  readonly "is-valid": string;
};
export = styles;

