/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "action-button": string;
  readonly "action-link": string;
  readonly "actions": string;
  readonly "close-icon": string;
  readonly "description": string;
  readonly "icon": string;
  readonly "is-action-button-minimal": string;
  readonly "is-action-button-outline": string;
  readonly "is-error": string;
  readonly "is-info": string;
  readonly "is-success": string;
  readonly "is-warning": string;
  readonly "notice": string;
  readonly "title": string;
};
export = styles;

