/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "chevron": string;
  readonly "dropdown": string;
  readonly "dropdown-children": string;
  readonly "is-up": string;
};
export = styles;

