/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "external-link-indicator": string;
  readonly "group": string;
  readonly "group-label": string;
  readonly "is-root": string;
  readonly "is-submenu": string;
  readonly "item": string;
  readonly "item-children": string;
  readonly "item-content": string;
  readonly "item-description": string;
  readonly "item-label": string;
  readonly "item-prefix": string;
  readonly "item-selection-indicator": string;
  readonly "item-shortcut": string;
  readonly "item-suffix": string;
  readonly "item-trailing": string;
  readonly "list": string;
  readonly "popup": string;
  readonly "positioner": string;
  readonly "radio-group": string;
  readonly "radio-selection-icon": string;
  readonly "separator": string;
  readonly "submenu-chevron": string;
};
export = styles;

