/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "column": string;
  readonly "grid-overlay-tile-in": string;
  readonly "has-rows": string;
  readonly "is-active": string;
  readonly "overlay": string;
  readonly "row": string;
};
export = styles;

