/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "exit-overlay": string;
  readonly "wp-grid-item-exit-opacity": string;
  readonly "wp-grid-item-exit-scale": string;
};
export = styles;

