/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "is-horizontal-only": string;
  readonly "resize-handle": string;
  readonly "resize-handle-slot": string;
};
export = styles;

