/**
 * External dependencies
 */
import ReactMarkdown from 'react-markdown';
import { storiesOf } from '@storybook/react';
import { text, select, withKnobs } from '@storybook/addon-knobs';

/**
 * Internal dependencies
 */
import Dashicon from '../';
import readme from '../README.md';

const decorateWordPressUI = ( story ) => (
	<div className="wp-core-ui">
		{ story() }
	</div>
);

const defaultInfoConfig = {
	header: true,
	inline: true,
	propTables: false,
	styles: ( style ) => ( { ...style, header: { ...style.header, h1: { display: 'none' } } } ),
};

storiesOf( 'Components', module )
	.addDecorator( decorateWordPressUI )
	.addDecorator( withKnobs )
	.addWithInfo(
		'Dashicon',
		( <ReactMarkdown source={ readme } /> ),
		() => (
			<Dashicon
				className={ text( 'className', '' ) }
				icon={ select( 'icon', {
					'admin-appearance': 'admin-appearance',
					'admin-collapse': 'admin-collapse',
					'admin-comments': 'admin-comments',
					'admin-customizer': 'admin-customizer',
					'admin-generic': 'admin-generic',
					'admin-home': 'admin-home',
					'admin-links': 'admin-links',
					'admin-media': 'admin-media',
					'admin-multisite': 'admin-multisite',
					'admin-network': 'admin-network',
					'admin-page': 'admin-page',
					'admin-plugins': 'admin-plugins',
					'admin-post': 'admin-post',
					'admin-settings': 'admin-settings',
					'admin-site-alt': 'admin-site-alt',
					'admin-site-alt2': 'admin-site-alt2',
					'admin-site-alt3': 'admin-site-alt3',
					'admin-site': 'admin-site',
					'admin-tools': 'admin-tools',
					'admin-users': 'admin-users',
					album: 'album',
					'align-center': 'align-center',
					'align-full-width': 'align-full-width',
					'align-left': 'align-left',
					'align-none': 'align-none',
					'align-right': 'align-right',
					'align-wide': 'align-wide',
					analytics: 'analytics',
					archive: 'archive',
					'arrow-down-alt': 'arrow-down-alt',
					'arrow-down-alt2': 'arrow-down-alt2',
					'arrow-down': 'arrow-down',
					'arrow-left-alt': 'arrow-left-alt',
					'arrow-left-alt2': 'arrow-left-alt2',
					'arrow-left': 'arrow-left',
					'arrow-right-alt': 'arrow-right-alt',
					'arrow-right-alt2': 'arrow-right-alt2',
					'arrow-right': 'arrow-right',
					'arrow-up-alt': 'arrow-up-alt',
					'arrow-up-alt2': 'arrow-up-alt2',
					'arrow-up': 'arrow-up',
					art: 'art',
					awards: 'awards',
					backup: 'backup',
					'book-alt': 'book-alt',
					book: 'book',
					'buddicons-activity': 'buddicons-activity',
					'buddicons-buddypress-logo': 'buddicons-buddypress-logo',
					'buddicons-community': 'buddicons-community',
					'buddicons-forums': 'buddicons-forums',
					'buddicons-friends': 'buddicons-friends',
					'buddicons-groups': 'buddicons-groups',
					'buddicons-pm': 'buddicons-pm',
					'buddicons-replies': 'buddicons-replies',
					'buddicons-topics': 'buddicons-topics',
					'buddicons-tracking': 'buddicons-tracking',
					'buddipress-bbpress-logo': 'buddipress-bbpress-logo',
					building: 'building',
					businessman: 'businessman',
					button: 'button',
					'calendar-alt': 'calendar-alt',
					calendar: 'calendar',
					camera: 'camera',
					carrot: 'carrot',
					cart: 'cart',
					category: 'category',
					'chart-area': 'chart-area',
					'chart-bar': 'chart-bar',
					'chart-line': 'chart-line',
					'chart-pie': 'chart-pie',
					clipboard: 'clipboard',
					clock: 'clock',
					cloud: 'cloud',
					'controls-back': 'controls-back',
					'controls-forward': 'controls-forward',
					'controls-pause': 'controls-pause',
					'controls-play': 'controls-play',
					'controls-repeat': 'controls-repeat',
					'controls-skipback': 'controls-skipback',
					'controls-skipforward': 'controls-skipforward',
					'controls-volumeoff': 'controls-volumeoff',
					'controls-volumeon': 'controls-volumeon',
					dashboard: 'dashboard',
					desktop: 'desktop',
					dismiss: 'dismiss',
					download: 'download',
					edit: 'edit',
					'editor-aligncenter': 'editor-aligncenter',
					'editor-alignleft': 'editor-alignleft',
					'editor-alignright': 'editor-alignright',
					'editor-bold': 'editor-bold',
					'editor-break': 'editor-break',
					'editor-code': 'editor-code',
					'editor-contract': 'editor-contract',
					'editor-customchar': 'editor-customchar',
					'editor-expand': 'editor-expand',
					'editor-help': 'editor-help',
					'editor-indent': 'editor-indent',
					'editor-insertmore': 'editor-insertmore',
					'editor-italic': 'editor-italic',
					'editor-justify': 'editor-justify',
					'editor-kitchensink': 'editor-kitchensink',
					'editor-ol': 'editor-ol',
					'editor-outdent': 'editor-outdent',
					'editor-paragraph': 'editor-paragraph',
					'editor-paste-text': 'editor-paste-text',
					'editor-paste-word': 'editor-paste-word',
					'editor-quote': 'editor-quote',
					'editor-removeformatting': 'editor-removeformatting',
					'editor-rtl': 'editor-rtl',
					'editor-spellcheck': 'editor-spellcheck',
					'editor-strikethrough': 'editor-strikethrough',
					'editor-table': 'editor-table',
					'editor-textcolor': 'editor-textcolor',
					'editor-ul': 'editor-ul',
					'editor-underline': 'editor-underline',
					'editor-unlink': 'editor-unlink',
					'editor-video': 'editor-video',
					ellipsis: 'ellipsis',
					'email-alt': 'email-alt',
					'email-alt2': 'email-alt2',
					email: 'email',
					'excerpt-view': 'excerpt-view',
					external: 'external',
					'facebook-alt': 'facebook-alt',
					facebook: 'facebook',
					feedback: 'feedback',
					filter: 'filter',
					flag: 'flag',
					'format-aside': 'format-aside',
					'format-audio': 'format-audio',
					'format-chat': 'format-chat',
					'format-gallery': 'format-gallery',
					'format-image': 'format-image',
					'format-quote': 'format-quote',
					'format-status': 'format-status',
					'format-video': 'format-video',
					forms: 'forms',
					googleplus: 'googleplus',
					'grid-view': 'grid-view',
					groups: 'groups',
					hammer: 'hammer',
					heading: 'heading',
					heart: 'heart',
					hidden: 'hidden',
					html: 'html',
					'id-alt': 'id-alt',
					id: 'id',
					'image-crop': 'image-crop',
					'image-filter': 'image-filter',
					'image-flip-horizontal': 'image-flip-horizontal',
					'image-flip-vertical': 'image-flip-vertical',
					'image-rotate-left': 'image-rotate-left',
					'image-rotate-right': 'image-rotate-right',
					'image-rotate': 'image-rotate',
					'images-alt': 'images-alt',
					'images-alt2': 'images-alt2',
					'index-card': 'index-card',
					info: 'info',
					insert: 'insert',
					laptop: 'laptop',
					layout: 'layout',
					leftright: 'leftright',
					lightbulb: 'lightbulb',
					'list-view': 'list-view',
					'location-alt': 'location-alt',
					location: 'location',
					lock: 'lock',
					marker: 'marker',
					'media-archive': 'media-archive',
					'media-audio': 'media-audio',
					'media-code': 'media-code',
					'media-default': 'media-default',
					'media-document': 'media-document',
					'media-interactive': 'media-interactive',
					'media-spreadsheet': 'media-spreadsheet',
					'media-text': 'media-text',
					'media-video': 'media-video',
					megaphone: 'megaphone',
					'menu-alt': 'menu-alt',
					menu: 'menu',
					microphone: 'microphone',
					migrate: 'migrate',
					minus: 'minus',
					money: 'money',
					move: 'move',
					nametag: 'nametag',
					networking: 'networking',
					'no-alt': 'no-alt',
					no: 'no',
					palmtree: 'palmtree',
					paperclip: 'paperclip',
					performance: 'performance',
					phone: 'phone',
					'playlist-audio': 'playlist-audio',
					'playlist-video': 'playlist-video',
					'plus-alt': 'plus-alt',
					'plus-light': 'plus-light',
					plus: 'plus',
					portfolio: 'portfolio',
					'post-status': 'post-status',
					pressthis: 'pressthis',
					products: 'products',
					randomize: 'randomize',
					redo: 'redo',
					rss: 'rss',
					saved: 'saved',
					schedule: 'schedule',
					screenoptions: 'screenoptions',
					search: 'search',
					'share-alt': 'share-alt',
					'share-alt2': 'share-alt2',
					share: 'share',
					'shield-alt': 'shield-alt',
					shield: 'shield',
					slides: 'slides',
					smartphone: 'smartphone',
					smiley: 'smiley',
					sort: 'sort',
					sos: 'sos',
					'star-empty': 'star-empty',
					'star-filled': 'star-filled',
					'star-half': 'star-half',
					sticky: 'sticky',
					store: 'store',
					'table-col-delete': 'table-col-delete',
					'table-col-after': 'table-col-after',
					'table-col-before': 'table-col-before',
					'table-row-delete': 'table-row-delete',
					'table-row-after': 'table-row-after',
					'table-row-before': 'table-row-before',
					tablet: 'tablet',
					tag: 'tag',
					tagcloud: 'tagcloud',
					testimonial: 'testimonial',
					text: 'text',
					'thumbs-down': 'thumbs-down',
					'thumbs-up': 'thumbs-up',
					'tickets-alt': 'tickets-alt',
					tickets: 'tickets',
					translation: 'translation',
					trash: 'trash',
					twitter: 'twitter',
					undo: 'undo',
					'universal-access-alt': 'universal-access-alt',
					'universal-access': 'universal-access',
					unlock: 'unlock',
					update: 'update',
					upload: 'upload',
					vault: 'vault',
					'video-alt': 'video-alt',
					'video-alt2': 'video-alt2',
					'video-alt3': 'video-alt3',
					visibility: 'visibility',
					warning: 'warning',
					'welcome-add-page': 'welcome-add-page',
					'welcome-comments': 'welcome-comments',
					'welcome-learn-more': 'welcome-learn-more',
					'welcome-view-site': 'welcome-view-site',
					'welcome-widgets-menus': 'welcome-widgets-menus',
					'welcome-write-blog': 'welcome-write-blog',
					'wordpress-alt': 'wordpress-alt',
					wordpress: 'wordpress',
					yes: 'yes',
				}, 'wordpress' ) }
			/>
		),
		defaultInfoConfig
	);
