/*
 * This file is generated by the @wordpress/terrazzo-plugin-known-wpds-css-variables plugin.
 * Do not edit this file directly.
 */

export const tokens = {
	'--wpds-border-radius-xs': {
		$description: 'Buttons and other elements nested inside controls.',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 1,
					unit: 'px',
				},
				css: '1px',
			},
		},
	},
	'--wpds-border-radius-sm': {
		$description: 'Standalone buttons, inputs, and compact controls.',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 2,
					unit: 'px',
				},
				css: '2px',
			},
		},
	},
	'--wpds-border-radius-md': {
		$description: 'Menus, popovers, and other small portaled overlays.',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 4,
					unit: 'px',
				},
				css: '4px',
			},
		},
	},
	'--wpds-border-radius-lg': {
		$description:
			'Cards, dialogs, notices, and other larger content containers.',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 8,
					unit: 'px',
				},
				css: '8px',
			},
		},
	},
	'--wpds-border-radius-xl': {
		$description: 'Page and app shell surfaces.',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 12,
					unit: 'px',
				},
				css: '12px',
			},
		},
	},
	'--wpds-border-width-xs': {
		$description: 'Extra small width',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 1,
					unit: 'px',
				},
				css: '1px',
			},
		},
	},
	'--wpds-border-width-sm': {
		$description: 'Small width',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 2,
					unit: 'px',
				},
				css: '2px',
			},
		},
	},
	'--wpds-border-width-md': {
		$description: 'Medium width',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 4,
					unit: 'px',
				},
				css: '4px',
			},
		},
	},
	'--wpds-border-width-lg': {
		$description: 'Large width',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 8,
					unit: 'px',
				},
				css: '8px',
			},
		},
	},
	'--wpds-border-width-focus': {
		$description: 'Border width for focus ring',
		$type: 'dimension',
		group: 'border',
		modes: {
			default: {
				$value: {
					value: 2,
					unit: 'px',
				},
				css: '2px',
			},
		},
	},
	'--wpds-color-background-surface-neutral': {
		$description: 'Background color for surfaces with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.988, 0.988, 0.988 ],
					hex: '#fcfcfc',
					alpha: 1,
				},
				css: '#fcfcfc',
			},
		},
	},
	'--wpds-color-background-surface-neutral-strong': {
		$description: 'Background color for surfaces with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 1, 1 ],
					hex: '#fff',
					alpha: 1,
				},
				css: '#fff',
			},
		},
	},
	'--wpds-color-background-surface-neutral-weak': {
		$description: 'Background color for surfaces with weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.957, 0.957, 0.957 ],
					hex: '#f4f4f4',
					alpha: 1,
				},
				css: '#f4f4f4',
			},
		},
	},
	'--wpds-color-background-surface-brand': {
		$description:
			'Background color for surfaces with brand tone and normal emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-surface-success': {
		$description:
			'Background color for surfaces with success tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.761, 0.973, 0.792 ],
					hex: '#c2f8ca',
					alpha: 1,
				},
				css: '#c2f8ca',
			},
		},
	},
	'--wpds-color-background-surface-success-weak': {
		$description:
			'Background color for surfaces with success tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.922, 1, 0.929 ],
					hex: '#ebffed',
					alpha: 1,
				},
				css: '#ebffed',
			},
		},
	},
	'--wpds-color-background-surface-info': {
		$description:
			'Background color for surfaces with info tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.871, 0.922, 0.98 ],
					hex: '#deebfa',
					alpha: 1,
				},
				css: '#deebfa',
			},
		},
	},
	'--wpds-color-background-surface-info-weak': {
		$description:
			'Background color for surfaces with info tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.953, 0.976, 1 ],
					hex: '#f3f9ff',
					alpha: 1,
				},
				css: '#f3f9ff',
			},
		},
	},
	'--wpds-color-background-surface-warning': {
		$description:
			'Background color for surfaces with warning tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.992, 0.902, 0.745 ],
					hex: '#fde6be',
					alpha: 1,
				},
				css: '#fde6be',
			},
		},
	},
	'--wpds-color-background-surface-warning-weak': {
		$description:
			'Background color for surfaces with warning tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 0.969, 0.882 ],
					hex: '#fff7e1',
					alpha: 1,
				},
				css: '#fff7e1',
			},
		},
	},
	'--wpds-color-background-surface-caution': {
		$description:
			'Background color for surfaces with caution tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.996, 0.914, 0.584 ],
					hex: '#fee995',
					alpha: 1,
				},
				css: '#fee995',
			},
		},
	},
	'--wpds-color-background-surface-caution-weak': {
		$description:
			'Background color for surfaces with caution tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 0.976, 0.792 ],
					hex: '#fff9ca',
					alpha: 1,
				},
				css: '#fff9ca',
			},
		},
	},
	'--wpds-color-background-surface-error': {
		$description:
			'Background color for surfaces with error tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.98, 0.898, 0.882 ],
					hex: '#fae5e1',
					alpha: 1,
				},
				css: '#fae5e1',
			},
		},
	},
	'--wpds-color-background-surface-error-weak': {
		$description:
			'Background color for surfaces with error tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 0.965, 0.961 ],
					hex: '#fff6f5',
					alpha: 1,
				},
				css: '#fff6f5',
			},
		},
	},
	'--wpds-color-background-interactive-neutral': {
		$description:
			'Solid background color for neutral interactive controls, such as input fields and unchecked checkboxes.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 1, 1 ],
					hex: '#fff',
					alpha: 1,
				},
				css: '#fff',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-active': {
		$description:
			'Solid background color for neutral interactive controls that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 1, 1 ],
					hex: '#fff',
					alpha: 1,
				},
				css: '#fff',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-disabled': {
		$description:
			'Solid background color for neutral interactive controls in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 1, 1 ],
					hex: '#fff',
					alpha: 1,
				},
				css: '#fff',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-strong': {
		$description:
			'Background color for interactive elements with neutral tone and strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.176, 0.176, 0.176 ],
					hex: '#2d2d2d',
					alpha: 1,
				},
				css: '#2d2d2d',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-strong-active': {
		$description:
			'Background color for interactive elements with neutral tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.118, 0.118, 0.118 ],
					hex: '#1e1e1e',
					alpha: 1,
				},
				css: '#1e1e1e',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-strong-disabled': {
		$description:
			'Background color for interactive elements with neutral tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.902, 0.902, 0.902 ],
					hex: '#e6e6e6',
					alpha: 1,
				},
				css: '#e6e6e6',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-weak': {
		$description:
			'Background color for interactive elements with neutral tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-weak-active': {
		$description:
			'Background color for interactive elements with neutral tone and weak emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.929, 0.929, 0.929 ],
					hex: '#ededed',
					alpha: 1,
				},
				css: '#ededed',
			},
		},
	},
	'--wpds-color-background-interactive-neutral-weak-disabled': {
		$description:
			'Background color for interactive elements with neutral tone and weak emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-interactive-brand-strong': {
		$description:
			'Background color for interactive elements with brand tone and strong emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-brand-strong-active': {
		$description:
			'Background color for interactive elements with brand tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-brand-strong-disabled': {
		$description:
			'Background color for interactive elements with brand tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-brand-weak': {
		$description:
			'Background color for interactive elements with brand tone and weak emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-brand-weak-active': {
		$description:
			'Background color for interactive elements with brand tone and weak emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-brand-weak-disabled': {
		$description:
			'Background color for interactive elements with brand tone and weak emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-interactive-error': {
		$description:
			'Background color for interactive elements with error tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-interactive-error-active': {
		$description:
			'Background color for interactive elements with error tone and normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 1, 0.965, 0.961 ],
					hex: '#fff6f5',
					alpha: 1,
				},
				css: '#fff6f5',
			},
		},
	},
	'--wpds-color-background-interactive-error-disabled': {
		$description:
			'Background color for interactive elements with error tone and normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-interactive-error-strong': {
		$description:
			'Background color for interactive elements with error tone and strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-background-interactive-error-strong-active': {
		$description:
			'Background color for interactive elements with error tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.725, 0, 0 ],
					hex: '#b90000',
					alpha: 1,
				},
				css: '#b90000',
			},
		},
	},
	'--wpds-color-background-interactive-error-strong-disabled': {
		$description:
			'Background color for interactive elements with error tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.902, 0.902, 0.902 ],
					hex: '#e6e6e6',
					alpha: 1,
				},
				css: '#e6e6e6',
			},
		},
	},
	'--wpds-color-background-interactive-error-weak': {
		$description:
			'Background color for interactive elements with error tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-interactive-error-weak-active': {
		$description:
			'Background color for interactive elements with error tone and weak emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.98, 0.898, 0.882 ],
					hex: '#fae5e1',
					alpha: 1,
				},
				css: '#fae5e1',
			},
		},
	},
	'--wpds-color-background-interactive-error-weak-disabled': {
		$description:
			'Background color for interactive elements with error tone and weak emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0, 0 ],
					alpha: 0,
				},
				css: '#0000',
			},
		},
	},
	'--wpds-color-background-track-neutral-weak': {
		$description:
			'Background color for tracks with a neutral tone and weak emphasis (eg. scrollbar track).',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.941, 0.941, 0.941 ],
					hex: '#f0f0f0',
					alpha: 1,
				},
				css: '#f0f0f0',
			},
		},
	},
	'--wpds-color-background-track-neutral': {
		$description:
			'Background color for tracks with a neutral tone and normal emphasis (eg. slider or progressbar track).',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.859, 0.859, 0.859 ],
					hex: '#dbdbdb',
					alpha: 1,
				},
				css: '#dbdbdb',
			},
		},
	},
	'--wpds-color-background-thumb-neutral-weak': {
		$description:
			'Background color for thumbs with a neutral tone and weak emphasis (eg. scrollbar thumb).',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-background-thumb-neutral-weak-active': {
		$description:
			'Background color for thumbs with a neutral tone and weak emphasis (eg. scrollbar thumb) that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.431, 0.431, 0.431 ],
					hex: '#6e6e6e',
					alpha: 1,
				},
				css: '#6e6e6e',
			},
		},
	},
	'--wpds-color-background-thumb-brand': {
		$description:
			'Background color for thumbs with a brand tone and normal emphasis (eg. slider thumb and filled track).',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-thumb-brand-active': {
		$description:
			'Background color for thumbs with a brand tone and normal emphasis (eg. slider thumb and filled track) that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-thumb-brand-disabled': {
		$description:
			'Background color for thumbs with a brand tone and normal emphasis (eg. slider thumb and filled track), in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-background-thumb-neutral-weak-disabled': {
		$description:
			'Background color for thumbs with a neutral tone and weak emphasis (eg. scrollbar thumb), in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.859, 0.859, 0.859 ],
					hex: '#dbdbdb',
					alpha: 1,
				},
				css: '#dbdbdb',
			},
		},
	},
	'--wpds-color-foreground-content-neutral': {
		$description:
			'Foreground color for content like text with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.118, 0.118, 0.118 ],
					hex: '#1e1e1e',
					alpha: 1,
				},
				css: '#1e1e1e',
			},
		},
	},
	'--wpds-color-foreground-content-neutral-weak': {
		$description:
			'Foreground color for content like text with weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.439, 0.439, 0.439 ],
					hex: '#707070',
					alpha: 1,
				},
				css: '#707070',
			},
		},
	},
	'--wpds-color-foreground-content-success': {
		$description:
			'Foreground color for content like text with success tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.161, 0 ],
					hex: '#002900',
					alpha: 1,
				},
				css: '#002900',
			},
		},
	},
	'--wpds-color-foreground-content-success-weak': {
		$description:
			'Foreground color for content like text with success tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.502, 0.188 ],
					hex: '#008030',
					alpha: 1,
				},
				css: '#008030',
			},
		},
	},
	'--wpds-color-foreground-content-info': {
		$description:
			'Foreground color for content like text with info tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.106, 0.31 ],
					hex: '#001b4f',
					alpha: 1,
				},
				css: '#001b4f',
			},
		},
	},
	'--wpds-color-foreground-content-info-weak': {
		$description:
			'Foreground color for content like text with info tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.42, 0.843 ],
					hex: '#006bd7',
					alpha: 1,
				},
				css: '#006bd7',
			},
		},
	},
	'--wpds-color-foreground-content-warning': {
		$description:
			'Foreground color for content like text with warning tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.18, 0.098, 0 ],
					hex: '#2e1900',
					alpha: 1,
				},
				css: '#2e1900',
			},
		},
	},
	'--wpds-color-foreground-content-warning-weak': {
		$description:
			'Foreground color for content like text with warning tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.576, 0.388, 0 ],
					hex: '#936300',
					alpha: 1,
				},
				css: '#936300',
			},
		},
	},
	'--wpds-color-foreground-content-caution': {
		$description:
			'Foreground color for content like text with caution tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.157, 0.114, 0 ],
					hex: '#281d00',
					alpha: 1,
				},
				css: '#281d00',
			},
		},
	},
	'--wpds-color-foreground-content-caution-weak': {
		$description:
			'Foreground color for content like text with caution tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.514, 0.416, 0 ],
					hex: '#836a00',
					alpha: 1,
				},
				css: '#836a00',
			},
		},
	},
	'--wpds-color-foreground-content-error': {
		$description:
			'Foreground color for content like text with error tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.278, 0, 0 ],
					hex: '#470000',
					alpha: 1,
				},
				css: '#470000',
			},
		},
	},
	'--wpds-color-foreground-content-error-weak': {
		$description:
			'Foreground color for content like text with error tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral': {
		$description:
			'Foreground color for interactive elements with neutral tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.118, 0.118, 0.118 ],
					hex: '#1e1e1e',
					alpha: 1,
				},
				css: '#1e1e1e',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-active': {
		$description:
			'Foreground color for interactive elements with neutral tone and normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.118, 0.118, 0.118 ],
					hex: '#1e1e1e',
					alpha: 1,
				},
				css: '#1e1e1e',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-disabled': {
		$description:
			'Foreground color for interactive elements with neutral tone and normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-strong': {
		$description:
			'Foreground color for interactive elements with neutral tone and strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.941, 0.941, 0.941 ],
					hex: '#f0f0f0',
					alpha: 1,
				},
				css: '#f0f0f0',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-strong-active': {
		$description:
			'Foreground color for interactive elements with neutral tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.941, 0.941, 0.941 ],
					hex: '#f0f0f0',
					alpha: 1,
				},
				css: '#f0f0f0',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-strong-disabled': {
		$description:
			'Foreground color for interactive elements with neutral tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-weak': {
		$description:
			'Foreground color for interactive elements with neutral tone and weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.439, 0.439, 0.439 ],
					hex: '#707070',
					alpha: 1,
				},
				css: '#707070',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-weak-active': {
		$description:
			'Foreground color for interactive elements with neutral tone and weak emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.118, 0.118, 0.118 ],
					hex: '#1e1e1e',
					alpha: 1,
				},
				css: '#1e1e1e',
			},
		},
	},
	'--wpds-color-foreground-interactive-neutral-weak-disabled': {
		$description:
			'Foreground color for interactive elements with neutral tone and weak emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-foreground-interactive-brand': {
		$description:
			'Foreground color for interactive elements with brand tone and normal emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-brand-active': {
		$description:
			'Foreground color for interactive elements with brand tone and normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-brand-disabled': {
		$description:
			'Foreground color for interactive elements with brand tone and normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-brand-strong': {
		$description:
			'Foreground color for interactive elements with brand tone and strong emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-brand-strong-active': {
		$description:
			'Foreground color for interactive elements with brand tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-brand-strong-disabled': {
		$description:
			'Foreground color for interactive elements with brand tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-foreground-interactive-error': {
		$description:
			'Foreground color for interactive elements with error tone and normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-foreground-interactive-error-active': {
		$description:
			'Foreground color for interactive elements with error tone and normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.278, 0, 0 ],
					hex: '#470000',
					alpha: 1,
				},
				css: '#470000',
			},
		},
	},
	'--wpds-color-foreground-interactive-error-disabled': {
		$description:
			'Foreground color for interactive elements with error tone and normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-foreground-interactive-error-strong': {
		$description:
			'Foreground color for interactive elements with error tone and strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.949, 0.937, 0.937 ],
					hex: '#f2efef',
					alpha: 1,
				},
				css: '#f2efef',
			},
		},
	},
	'--wpds-color-foreground-interactive-error-strong-active': {
		$description:
			'Foreground color for interactive elements with error tone and strong emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.949, 0.937, 0.937 ],
					hex: '#f2efef',
					alpha: 1,
				},
				css: '#f2efef',
			},
		},
	},
	'--wpds-color-foreground-interactive-error-strong-disabled': {
		$description:
			'Foreground color for interactive elements with error tone and strong emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-stroke-surface-neutral': {
		$description:
			'Decorative stroke color used to define neutrally-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.859, 0.859, 0.859 ],
					hex: '#dbdbdb',
					alpha: 1,
				},
				css: '#dbdbdb',
			},
		},
	},
	'--wpds-color-stroke-surface-neutral-weak': {
		$description:
			'Decorative stroke color used to define neutrally-toned surface boundaries with weak emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.941, 0.941, 0.941 ],
					hex: '#f0f0f0',
					alpha: 1,
				},
				css: '#f0f0f0',
			},
		},
	},
	'--wpds-color-stroke-surface-neutral-strong': {
		$description:
			'Decorative stroke color used to define neutrally-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-stroke-surface-brand': {
		$description:
			'Decorative stroke color used to define brand-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-stroke-surface-brand-strong': {
		$description:
			'Decorative stroke color used to define brand-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-stroke-surface-success': {
		$description:
			'Decorative stroke color used to define success-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.573, 0.827, 0.616 ],
					hex: '#92d39d',
					alpha: 1,
				},
				css: '#92d39d',
			},
		},
	},
	'--wpds-color-stroke-surface-success-strong': {
		$description:
			'Decorative stroke color used to define success-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.502, 0.188 ],
					hex: '#008030',
					alpha: 1,
				},
				css: '#008030',
			},
		},
	},
	'--wpds-color-stroke-surface-info': {
		$description:
			'Decorative stroke color used to define info-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.678, 0.776, 0.886 ],
					hex: '#adc6e2',
					alpha: 1,
				},
				css: '#adc6e2',
			},
		},
	},
	'--wpds-color-stroke-surface-info-strong': {
		$description:
			'Decorative stroke color used to define info-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0, 0.42, 0.843 ],
					hex: '#006bd7',
					alpha: 1,
				},
				css: '#006bd7',
			},
		},
	},
	'--wpds-color-stroke-surface-warning': {
		$description:
			'Decorative stroke color used to define warning-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.882, 0.741, 0.486 ],
					hex: '#e1bd7c',
					alpha: 1,
				},
				css: '#e1bd7c',
			},
		},
	},
	'--wpds-color-stroke-surface-warning-strong': {
		$description:
			'Decorative stroke color used to define warning-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.576, 0.388, 0 ],
					hex: '#936300',
					alpha: 1,
				},
				css: '#936300',
			},
		},
	},
	'--wpds-color-stroke-surface-caution': {
		$description:
			'Decorative stroke color used to define caution-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.816, 0.761, 0.545 ],
					hex: '#d0c28b',
					alpha: 1,
				},
				css: '#d0c28b',
			},
		},
	},
	'--wpds-color-stroke-surface-caution-strong': {
		$description:
			'Decorative stroke color used to define caution-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.514, 0.416, 0 ],
					hex: '#836a00',
					alpha: 1,
				},
				css: '#836a00',
			},
		},
	},
	'--wpds-color-stroke-surface-error': {
		$description:
			'Decorative stroke color used to define error-toned surface boundaries with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.878, 0.686, 0.655 ],
					hex: '#e0afa7',
					alpha: 1,
				},
				css: '#e0afa7',
			},
		},
	},
	'--wpds-color-stroke-surface-error-strong': {
		$description:
			'Decorative stroke color used to define error-toned surface boundaries with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-stroke-interactive-neutral': {
		$description:
			'Accessible stroke color used for interactive neutrally-toned elements with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.553, 0.553, 0.553 ],
					hex: '#8d8d8d',
					alpha: 1,
				},
				css: '#8d8d8d',
			},
		},
	},
	'--wpds-color-stroke-interactive-neutral-active': {
		$description:
			'Accessible stroke color used for interactive neutrally-toned elements with normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.431, 0.431, 0.431 ],
					hex: '#6e6e6e',
					alpha: 1,
				},
				css: '#6e6e6e',
			},
		},
	},
	'--wpds-color-stroke-interactive-neutral-disabled': {
		$description:
			'Accessible stroke color used for interactive neutrally-toned elements with normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.859, 0.859, 0.859 ],
					hex: '#dbdbdb',
					alpha: 1,
				},
				css: '#dbdbdb',
			},
		},
	},
	'--wpds-color-stroke-interactive-neutral-strong': {
		$description:
			'Accessible stroke color used for interactive neutrally-toned elements with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.431, 0.431, 0.431 ],
					hex: '#6e6e6e',
					alpha: 1,
				},
				css: '#6e6e6e',
			},
		},
	},
	'--wpds-color-stroke-interactive-brand': {
		$description:
			'Accessible stroke color used for interactive brand-toned elements with normal emphasis.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-stroke-interactive-brand-active': {
		$description:
			'Accessible stroke color used for interactive brand-toned elements with normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-stroke-interactive-brand-disabled': {
		$description:
			'Accessible stroke color used for interactive brand-toned elements with normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
	},
	'--wpds-color-stroke-interactive-error': {
		$description:
			'Accessible stroke color used for interactive error-toned elements with normal emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-stroke-interactive-error-active': {
		$description:
			'Accessible stroke color used for interactive error-toned elements with normal emphasis that are hovered, focused, or active.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.616, 0, 0 ],
					hex: '#9d0000',
					alpha: 1,
				},
				css: '#9d0000',
			},
		},
	},
	'--wpds-color-stroke-interactive-error-disabled': {
		$description:
			'Accessible stroke color used for interactive error-toned elements with normal emphasis, in their disabled state.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.859, 0.859, 0.859 ],
					hex: '#dbdbdb',
					alpha: 1,
				},
				css: '#dbdbdb',
			},
		},
	},
	'--wpds-color-stroke-interactive-error-strong': {
		$description:
			'Accessible stroke color used for interactive error-toned elements with strong emphasis.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.8, 0.094, 0.094 ],
					hex: '#cc1818',
					alpha: 1,
				},
				css: '#cc1818',
			},
		},
	},
	'--wpds-color-stroke-focus': {
		$description: 'Accessible stroke color applied to focus rings.',
		$type: 'color',
		group: 'color',
		modes: {
			default: {
				$value: {
					colorSpace: 'srgb',
					components: [ 0.22, 0.345, 0.914 ],
					hex: '#3858e9',
					alpha: 1,
				},
				css: '#3858e9',
			},
		},
	},
	'--wpds-cursor-control': {
		$description:
			'Cursor style for interactive controls that are not links (e.g. buttons, checkboxes, and toggles).',
		$type: 'string',
		group: 'cursor',
		modes: {
			default: {
				$value: 'pointer',
				css: 'pointer',
			},
		},
	},
	'--wpds-dimension-padding-xs': {
		$description: 'Extra small padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 4,
					unit: 'px',
				},
				css: '4px',
			},
		},
	},
	'--wpds-dimension-padding-sm': {
		$description: 'Small padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 8,
					unit: 'px',
				},
				css: '8px',
			},
		},
	},
	'--wpds-dimension-padding-md': {
		$description: 'Medium padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 12,
					unit: 'px',
				},
				css: '12px',
			},
		},
	},
	'--wpds-dimension-padding-lg': {
		$description: 'Large padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 16,
					unit: 'px',
				},
				css: '16px',
			},
		},
	},
	'--wpds-dimension-padding-xl': {
		$description: 'Extra large padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 20,
					unit: 'px',
				},
				css: '20px',
			},
		},
	},
	'--wpds-dimension-padding-2xl': {
		$description: '2x extra large padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 24,
					unit: 'px',
				},
				css: '24px',
			},
		},
	},
	'--wpds-dimension-padding-3xl': {
		$description: '3x extra large padding',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 32,
					unit: 'px',
				},
				css: '32px',
			},
		},
	},
	'--wpds-dimension-gap-xs': {
		$description: 'Extra small gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 4,
					unit: 'px',
				},
				css: '4px',
			},
		},
	},
	'--wpds-dimension-gap-sm': {
		$description: 'Small gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 8,
					unit: 'px',
				},
				css: '8px',
			},
		},
	},
	'--wpds-dimension-gap-md': {
		$description: 'Medium gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 12,
					unit: 'px',
				},
				css: '12px',
			},
		},
	},
	'--wpds-dimension-gap-lg': {
		$description: 'Large gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 16,
					unit: 'px',
				},
				css: '16px',
			},
		},
	},
	'--wpds-dimension-gap-xl': {
		$description: 'Extra large gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 24,
					unit: 'px',
				},
				css: '24px',
			},
		},
	},
	'--wpds-dimension-gap-2xl': {
		$description: '2x extra large gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 32,
					unit: 'px',
				},
				css: '32px',
			},
		},
	},
	'--wpds-dimension-gap-3xl': {
		$description: '3x extra large gap',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 40,
					unit: 'px',
				},
				css: '40px',
			},
		},
	},
	'--wpds-dimension-size-5xs': {
		$description: 'Notification indicators',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 4,
					unit: 'px',
				},
				css: '4px',
			},
		},
	},
	'--wpds-dimension-size-4xs': {
		$description:
			'Visual size for small interactive elements like resize handles',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 8,
					unit: 'px',
				},
				css: '8px',
			},
		},
	},
	'--wpds-dimension-size-3xs': {
		$description: 'Small markers',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 12,
					unit: 'px',
				},
				css: '12px',
			},
		},
	},
	'--wpds-dimension-size-2xs': {
		$description:
			'For small controls like checkboxes and radios, or small decorative icons',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 16,
					unit: 'px',
				},
				css: '16px',
			},
		},
	},
	'--wpds-dimension-size-xs': {
		$description: 'For medium sized icons',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 20,
					unit: 'px',
				},
				css: '20px',
			},
		},
	},
	'--wpds-dimension-size-sm': {
		$description: 'For icons and small buttons',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 24,
					unit: 'px',
				},
				css: '24px',
			},
		},
	},
	'--wpds-dimension-size-md': {
		$description: 'For medium-sized buttons and inputs',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 32,
					unit: 'px',
				},
				css: '32px',
			},
		},
	},
	'--wpds-dimension-size-lg': {
		$description: 'Default size for buttons and inputs',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 40,
					unit: 'px',
				},
				css: '40px',
			},
		},
	},
	'--wpds-dimension-surface-width-xs': {
		$description: 'Extra small surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 240,
					unit: 'px',
				},
				css: '240px',
			},
		},
	},
	'--wpds-dimension-surface-width-sm': {
		$description: 'Small surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 320,
					unit: 'px',
				},
				css: '320px',
			},
		},
	},
	'--wpds-dimension-surface-width-md': {
		$description: 'Medium surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 400,
					unit: 'px',
				},
				css: '400px',
			},
		},
	},
	'--wpds-dimension-surface-width-lg': {
		$description: 'Large surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 560,
					unit: 'px',
				},
				css: '560px',
			},
		},
	},
	'--wpds-dimension-surface-width-xl': {
		$description: 'Extra large surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 720,
					unit: 'px',
				},
				css: '720px',
			},
		},
	},
	'--wpds-dimension-surface-width-2xl': {
		$description: '2x extra large surface width',
		$type: 'dimension',
		group: 'dimension',
		modes: {
			default: {
				$value: {
					value: 960,
					unit: 'px',
				},
				css: '960px',
			},
		},
	},
	'--wpds-motion-duration-xs': {
		$description: 'Micro-delays and transition offsets',
		$type: 'duration',
		group: 'motion',
		modes: {
			default: {
				$value: {
					value: 50,
					unit: 'ms',
				},
				css: '50ms',
			},
		},
	},
	'--wpds-motion-duration-sm': {
		$description: 'Micro-interactions like focus rings and state changes',
		$type: 'duration',
		group: 'motion',
		modes: {
			default: {
				$value: {
					value: 100,
					unit: 'ms',
				},
				css: '100ms',
			},
		},
	},
	'--wpds-motion-duration-md': {
		$description: 'Standard transitions like menus and popovers',
		$type: 'duration',
		group: 'motion',
		modes: {
			default: {
				$value: {
					value: 200,
					unit: 'ms',
				},
				css: '200ms',
			},
		},
	},
	'--wpds-motion-duration-lg': {
		$description: 'Deliberate animations like slides and reveals',
		$type: 'duration',
		group: 'motion',
		modes: {
			default: {
				$value: {
					value: 300,
					unit: 'ms',
				},
				css: '300ms',
			},
		},
	},
	'--wpds-motion-duration-xl': {
		$description:
			'Extended animations like complex or multi-step transitions',
		$type: 'duration',
		group: 'motion',
		modes: {
			default: {
				$value: {
					value: 400,
					unit: 'ms',
				},
				css: '400ms',
			},
		},
	},
	'--wpds-motion-easing-subtle': {
		$description:
			'Nearly imperceptible easing for hover, color, and background transitions',
		$type: 'cubicBezier',
		group: 'motion',
		modes: {
			default: {
				$value: [ 0.15, 0, 0.15, 1 ],
				css: 'cubic-bezier(0.15, 0, 0.15, 1)',
			},
		},
	},
	'--wpds-motion-easing-balanced': {
		$description:
			'General-purpose easing for on-screen movement like resizing, morphing, and layout shifts',
		$type: 'cubicBezier',
		group: 'motion',
		modes: {
			default: {
				$value: [ 0.4, 0, 0.2, 1 ],
				css: 'cubic-bezier(0.4, 0, 0.2, 1)',
			},
		},
	},
	'--wpds-motion-easing-expressive': {
		$description:
			'Noticeable easing for enter/exit and spatial transitions like menus, popovers, dialogs, and drawers',
		$type: 'cubicBezier',
		group: 'motion',
		modes: {
			default: {
				$value: [ 0.25, 0, 0, 1 ],
				css: 'cubic-bezier(0.25, 0, 0, 1)',
			},
		},
	},
	'--wpds-typography-font-family-heading': {
		$description: 'Headings font family',
		$type: 'fontFamily',
		group: 'typography',
		modes: {
			default: {
				$value: [
					'-apple-system',
					'system-ui',
					'Segoe UI',
					'Roboto',
					'Oxygen-Sans',
					'Ubuntu',
					'Cantarell',
					'Helvetica Neue',
					'sans-serif',
				],
				css: '-apple-system, system-ui, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", sans-serif',
			},
		},
	},
	'--wpds-typography-font-family-body': {
		$description: 'Body font family',
		$type: 'fontFamily',
		group: 'typography',
		modes: {
			default: {
				$value: [
					'-apple-system',
					'system-ui',
					'Segoe UI',
					'Roboto',
					'Oxygen-Sans',
					'Ubuntu',
					'Cantarell',
					'Helvetica Neue',
					'sans-serif',
				],
				css: '-apple-system, system-ui, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", sans-serif',
			},
		},
	},
	'--wpds-typography-font-family-mono': {
		$description: 'Monospace font family',
		$type: 'fontFamily',
		group: 'typography',
		modes: {
			default: {
				$value: [ 'Menlo', 'Consolas', 'monaco', 'monospace' ],
				css: '"Menlo", "Consolas", monaco, monospace',
			},
		},
	},
	'--wpds-typography-font-size-xs': {
		$description: 'Extra small font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 11,
					unit: 'px',
				},
				css: '11px',
			},
		},
	},
	'--wpds-typography-font-size-sm': {
		$description: 'Small font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 12,
					unit: 'px',
				},
				css: '12px',
			},
		},
	},
	'--wpds-typography-font-size-md': {
		$description: 'Medium font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 13,
					unit: 'px',
				},
				css: '13px',
			},
		},
	},
	'--wpds-typography-font-size-lg': {
		$description: 'Large font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 15,
					unit: 'px',
				},
				css: '15px',
			},
		},
	},
	'--wpds-typography-font-size-xl': {
		$description: 'Extra large font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 20,
					unit: 'px',
				},
				css: '20px',
			},
		},
	},
	'--wpds-typography-font-size-2xl': {
		$description: '2X large font size',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 32,
					unit: 'px',
				},
				css: '32px',
			},
		},
	},
	'--wpds-typography-line-height-xs': {
		$description: 'Extra small line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 16,
					unit: 'px',
				},
				css: '16px',
			},
		},
	},
	'--wpds-typography-line-height-sm': {
		$description: 'Small line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 20,
					unit: 'px',
				},
				css: '20px',
			},
		},
	},
	'--wpds-typography-line-height-md': {
		$description: 'Medium line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 24,
					unit: 'px',
				},
				css: '24px',
			},
		},
	},
	'--wpds-typography-line-height-lg': {
		$description: 'Large line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 28,
					unit: 'px',
				},
				css: '28px',
			},
		},
	},
	'--wpds-typography-line-height-xl': {
		$description: 'Extra large line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 32,
					unit: 'px',
				},
				css: '32px',
			},
		},
	},
	'--wpds-typography-line-height-2xl': {
		$description: '2X large line height',
		$type: 'dimension',
		group: 'typography',
		modes: {
			default: {
				$value: {
					value: 40,
					unit: 'px',
				},
				css: '40px',
			},
		},
	},
	'--wpds-typography-font-weight-default': {
		$description: 'Baseline text weight for body copy and UI text',
		$type: 'fontWeight',
		group: 'typography',
		modes: {
			default: {
				$value: 400,
				css: '400',
			},
		},
	},
	'--wpds-typography-font-weight-emphasis': {
		$description: 'Elevated text weight for labels, controls, and headings',
		$type: 'fontWeight',
		group: 'typography',
		modes: {
			default: {
				$value: 600,
				css: '600',
			},
		},
	},
};

export const groups = {
	border: [
		'--wpds-border-radius-xs',
		'--wpds-border-radius-sm',
		'--wpds-border-radius-md',
		'--wpds-border-radius-lg',
		'--wpds-border-radius-xl',
		'--wpds-border-width-xs',
		'--wpds-border-width-sm',
		'--wpds-border-width-md',
		'--wpds-border-width-lg',
		'--wpds-border-width-focus',
	],
	color: [
		'--wpds-color-background-surface-neutral',
		'--wpds-color-background-surface-neutral-strong',
		'--wpds-color-background-surface-neutral-weak',
		'--wpds-color-background-surface-brand',
		'--wpds-color-background-surface-success',
		'--wpds-color-background-surface-success-weak',
		'--wpds-color-background-surface-info',
		'--wpds-color-background-surface-info-weak',
		'--wpds-color-background-surface-warning',
		'--wpds-color-background-surface-warning-weak',
		'--wpds-color-background-surface-caution',
		'--wpds-color-background-surface-caution-weak',
		'--wpds-color-background-surface-error',
		'--wpds-color-background-surface-error-weak',
		'--wpds-color-background-interactive-neutral',
		'--wpds-color-background-interactive-neutral-active',
		'--wpds-color-background-interactive-neutral-disabled',
		'--wpds-color-background-interactive-neutral-strong',
		'--wpds-color-background-interactive-neutral-strong-active',
		'--wpds-color-background-interactive-neutral-strong-disabled',
		'--wpds-color-background-interactive-neutral-weak',
		'--wpds-color-background-interactive-neutral-weak-active',
		'--wpds-color-background-interactive-neutral-weak-disabled',
		'--wpds-color-background-interactive-brand-strong',
		'--wpds-color-background-interactive-brand-strong-active',
		'--wpds-color-background-interactive-brand-strong-disabled',
		'--wpds-color-background-interactive-brand-weak',
		'--wpds-color-background-interactive-brand-weak-active',
		'--wpds-color-background-interactive-brand-weak-disabled',
		'--wpds-color-background-interactive-error',
		'--wpds-color-background-interactive-error-active',
		'--wpds-color-background-interactive-error-disabled',
		'--wpds-color-background-interactive-error-strong',
		'--wpds-color-background-interactive-error-strong-active',
		'--wpds-color-background-interactive-error-strong-disabled',
		'--wpds-color-background-interactive-error-weak',
		'--wpds-color-background-interactive-error-weak-active',
		'--wpds-color-background-interactive-error-weak-disabled',
		'--wpds-color-background-track-neutral-weak',
		'--wpds-color-background-track-neutral',
		'--wpds-color-background-thumb-neutral-weak',
		'--wpds-color-background-thumb-neutral-weak-active',
		'--wpds-color-background-thumb-brand',
		'--wpds-color-background-thumb-brand-active',
		'--wpds-color-background-thumb-brand-disabled',
		'--wpds-color-background-thumb-neutral-weak-disabled',
		'--wpds-color-foreground-content-neutral',
		'--wpds-color-foreground-content-neutral-weak',
		'--wpds-color-foreground-content-success',
		'--wpds-color-foreground-content-success-weak',
		'--wpds-color-foreground-content-info',
		'--wpds-color-foreground-content-info-weak',
		'--wpds-color-foreground-content-warning',
		'--wpds-color-foreground-content-warning-weak',
		'--wpds-color-foreground-content-caution',
		'--wpds-color-foreground-content-caution-weak',
		'--wpds-color-foreground-content-error',
		'--wpds-color-foreground-content-error-weak',
		'--wpds-color-foreground-interactive-neutral',
		'--wpds-color-foreground-interactive-neutral-active',
		'--wpds-color-foreground-interactive-neutral-disabled',
		'--wpds-color-foreground-interactive-neutral-strong',
		'--wpds-color-foreground-interactive-neutral-strong-active',
		'--wpds-color-foreground-interactive-neutral-strong-disabled',
		'--wpds-color-foreground-interactive-neutral-weak',
		'--wpds-color-foreground-interactive-neutral-weak-active',
		'--wpds-color-foreground-interactive-neutral-weak-disabled',
		'--wpds-color-foreground-interactive-brand',
		'--wpds-color-foreground-interactive-brand-active',
		'--wpds-color-foreground-interactive-brand-disabled',
		'--wpds-color-foreground-interactive-brand-strong',
		'--wpds-color-foreground-interactive-brand-strong-active',
		'--wpds-color-foreground-interactive-brand-strong-disabled',
		'--wpds-color-foreground-interactive-error',
		'--wpds-color-foreground-interactive-error-active',
		'--wpds-color-foreground-interactive-error-disabled',
		'--wpds-color-foreground-interactive-error-strong',
		'--wpds-color-foreground-interactive-error-strong-active',
		'--wpds-color-foreground-interactive-error-strong-disabled',
		'--wpds-color-stroke-surface-neutral',
		'--wpds-color-stroke-surface-neutral-weak',
		'--wpds-color-stroke-surface-neutral-strong',
		'--wpds-color-stroke-surface-brand',
		'--wpds-color-stroke-surface-brand-strong',
		'--wpds-color-stroke-surface-success',
		'--wpds-color-stroke-surface-success-strong',
		'--wpds-color-stroke-surface-info',
		'--wpds-color-stroke-surface-info-strong',
		'--wpds-color-stroke-surface-warning',
		'--wpds-color-stroke-surface-warning-strong',
		'--wpds-color-stroke-surface-caution',
		'--wpds-color-stroke-surface-caution-strong',
		'--wpds-color-stroke-surface-error',
		'--wpds-color-stroke-surface-error-strong',
		'--wpds-color-stroke-interactive-neutral',
		'--wpds-color-stroke-interactive-neutral-active',
		'--wpds-color-stroke-interactive-neutral-disabled',
		'--wpds-color-stroke-interactive-neutral-strong',
		'--wpds-color-stroke-interactive-brand',
		'--wpds-color-stroke-interactive-brand-active',
		'--wpds-color-stroke-interactive-brand-disabled',
		'--wpds-color-stroke-interactive-error',
		'--wpds-color-stroke-interactive-error-active',
		'--wpds-color-stroke-interactive-error-disabled',
		'--wpds-color-stroke-interactive-error-strong',
		'--wpds-color-stroke-focus',
	],
	cursor: [ '--wpds-cursor-control' ],
	dimension: [
		'--wpds-dimension-padding-xs',
		'--wpds-dimension-padding-sm',
		'--wpds-dimension-padding-md',
		'--wpds-dimension-padding-lg',
		'--wpds-dimension-padding-xl',
		'--wpds-dimension-padding-2xl',
		'--wpds-dimension-padding-3xl',
		'--wpds-dimension-gap-xs',
		'--wpds-dimension-gap-sm',
		'--wpds-dimension-gap-md',
		'--wpds-dimension-gap-lg',
		'--wpds-dimension-gap-xl',
		'--wpds-dimension-gap-2xl',
		'--wpds-dimension-gap-3xl',
		'--wpds-dimension-size-5xs',
		'--wpds-dimension-size-4xs',
		'--wpds-dimension-size-3xs',
		'--wpds-dimension-size-2xs',
		'--wpds-dimension-size-xs',
		'--wpds-dimension-size-sm',
		'--wpds-dimension-size-md',
		'--wpds-dimension-size-lg',
		'--wpds-dimension-surface-width-xs',
		'--wpds-dimension-surface-width-sm',
		'--wpds-dimension-surface-width-md',
		'--wpds-dimension-surface-width-lg',
		'--wpds-dimension-surface-width-xl',
		'--wpds-dimension-surface-width-2xl',
	],
	motion: [
		'--wpds-motion-duration-xs',
		'--wpds-motion-duration-sm',
		'--wpds-motion-duration-md',
		'--wpds-motion-duration-lg',
		'--wpds-motion-duration-xl',
		'--wpds-motion-easing-subtle',
		'--wpds-motion-easing-balanced',
		'--wpds-motion-easing-expressive',
	],
	typography: [
		'--wpds-typography-font-family-heading',
		'--wpds-typography-font-family-body',
		'--wpds-typography-font-family-mono',
		'--wpds-typography-font-size-xs',
		'--wpds-typography-font-size-sm',
		'--wpds-typography-font-size-md',
		'--wpds-typography-font-size-lg',
		'--wpds-typography-font-size-xl',
		'--wpds-typography-font-size-2xl',
		'--wpds-typography-line-height-xs',
		'--wpds-typography-line-height-sm',
		'--wpds-typography-line-height-md',
		'--wpds-typography-line-height-lg',
		'--wpds-typography-line-height-xl',
		'--wpds-typography-line-height-2xl',
		'--wpds-typography-font-weight-default',
		'--wpds-typography-font-weight-emphasis',
	],
};
