/* This file is generated by `npm run css-modules:generate`. Do not edit. */

declare const styles: {
  readonly "button": string;
  readonly "button-content": string;
  readonly "is-deselectable": string;
  readonly "is-icon": string;
  readonly "is-pressed": string;
  readonly "label": string;
  readonly "label-block": string;
};
export = styles;

