name: Check root dependencies

on:
    pull_request:
        paths:
            - 'package.json'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    check:
        name: Disallow new root dependencies
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        steps:
            - name: Checkout PR
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Check for new root dependencies
              env:
                  BASE_SHA: ${{ github.event.pull_request.base.sha }}
              run: npm run --workspace @wordpress/validation-tools check-root-dependencies -- --base "$BASE_SHA"
