name: 'Pull Request Labeler'
on:
    pull_request_target:
        types: [opened, synchronize]

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    auto_label_pull_request:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
              with:
                  dot: true
                  sync-labels: true
