name: Lint GitHub Actions workflows
on:
    workflow_call:

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    # Runs the actionlint GitHub Action workflow file linter.
    #
    # See https://github.com/rhysd/actionlint.
    #
    # This helps guard against common mistakes including strong type checking for expressions (${{ }}), security checks,
    # `run:` script checking, glob syntax validation, and more.
    actionlint:
        name: Run actionlint
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        timeout-minutes: 5
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Run actionlint
              uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # v1.7.12
              with:
                  args: '-color -verbose'

    # Runs the Zizmor GitHub Action workflow file linter.
    #
    # See https://github.com/zizmorcore/zizmor.
    #
    # This helps guard against supply chain attacks, unpinned dependencies, excessive permissions,
    # dangerous triggers, credential leaks, and sophisticated security vulnerabilities.
    zizmor:
        name: Run Zizmor
        runs-on: 'ubuntu-24.04'
        permissions:
            security-events: write
            actions: read
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

            - name: Run zizmor
              run: uvx zizmor@1.24.1 --persona=regular --format=sarif --strict-collection . > results.sarif
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@d1ba80a13dd99fba24a470575428917156a28b43 # v4.37.5
              with:
                  sarif_file: results.sarif
                  category: zizmor
